-- ============================================================
-- 楽天の受注を在庫へつなぐ（モール受注 → 販売予約 → 売却済）
--   2026-09-19（2026-09-19-rental-by-condition.sql の後に流す）
--
--   何度流しても同じ結果になる（create table if not exists / create or replace）。
--
--   入っているもの
--     1) 社内用ビュー inv_channel_stock_feed を anon から見えないようにする
--        （Supabaseの既定権限で公開キーから読めてしまっていた）
--     2) inventory_sale_orders（モールの受注明細。注文番号×明細番号×連番で一意）
--     3) inv_listing_product()（モールの商品コード・URLから商品を引く。推測はしない）
--     4) inv_sale_orders_apply()（受注を取り込んで在庫を確保する。冪等）
--     5) inv_sale_order_link()（商品を特定できなかった明細に人が商品を当てる）
--
--   あわせて Edge Function のデプロイと環境変数が必要です
--     supabase functions deploy rakuten-order-sync
--     RAKUTEN_RMS_SERVICE_SECRET / RAKUTEN_RMS_LICENSE_KEY
--   （画像同期の Rakuten Developers API とは別のAPI・別の資格情報です）
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 33-1) 内部用ビューを anon から見えないようにする
--
--     Supabaseの既定では、public スキーマに作ったビューに anon の
--     SELECT 権限が自動で付く（alter default privileges）。
--     grant を authenticated だけに書いても、その既定ぶんは消えないため、
--     社内用の在庫ビューが公開キーで読めてしまっていた。明示的に revoke する。
--     テーブルはRLSで守られているのでこの影響を受けない（ビューだけの話）。
-- ------------------------------------------------------------
revoke all on public.inv_channel_stock_feed from anon;

-- ------------------------------------------------------------
-- 33-2) モールの受注（楽天RMSなど）
--
--     同じ注文を何度取り込んでも在庫が二重に減らないよう、
--     「注文番号 × 明細番号 × 明細内の連番」で一意にする。
--     取り込み済みの行があれば、その明細はもう触らない。
--
--     実在庫の確保は inv_sale_reserve()（＝ inv_reserve_available_item）に任せる。
--     8RENTの予約中・貸出中は status が '在庫' ではないので、そもそも選ばれない。
-- ------------------------------------------------------------
create table if not exists public.inventory_sale_orders (
  id            bigint generated by default as identity primary key,
  channel       text not null default 'rakuten',
  order_number  text not null,                 -- モールの注文番号
  line_number   text not null,                 -- 明細番号
  unit_no       integer not null default 1,    -- 同じ明細で数量2以上のときの連番
  item_code     text,                          -- モール側の商品コード
  item_url      text,
  product_code  text references public.inventory_products(code) on delete set null,
  item_id       text references public.inventory_items(id) on delete set null,
  price         numeric,
  ordered_at    timestamptz,
  status        text not null default '受注',  -- 受注 / 発送済 / キャンセル / 未割当 / 在庫なし
  note          text,
  raw           jsonb,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  constraint inventory_sale_orders_uniq unique (channel, order_number, line_number, unit_no)
);

comment on table public.inventory_sale_orders is
  'モール（楽天など）の受注明細。注文番号×明細番号×連番で一意にしてあり、同じ注文を何度取り込んでも
   在庫は一度しか減らない。確保した個体は item_id に入る。';

create index if not exists inventory_sale_orders_status_idx
  on public.inventory_sale_orders (status, ordered_at desc);
create index if not exists inventory_sale_orders_item_idx
  on public.inventory_sale_orders (item_id);

drop trigger if exists inventory_sale_orders_touch on public.inventory_sale_orders;
create trigger inventory_sale_orders_touch before update on public.inventory_sale_orders
  for each row execute function public.inv_touch();

alter table public.inventory_sale_orders enable row level security;

drop policy if exists inventory_sale_orders_read on public.inventory_sale_orders;
create policy inventory_sale_orders_read on public.inventory_sale_orders
  for select to authenticated using (public.inv_role() in ('admin','member','viewer'));

-- ------------------------------------------------------------
-- 33-3) モールの商品コード・URLから商品を引く
--     推測はしない。external_item_code の一致か、正規化したURLの一致だけ。
-- ------------------------------------------------------------
create or replace function public.inv_listing_product(
  p_channel   text,
  p_item_code text,
  p_item_url  text
) returns text language sql stable set search_path = public as $$
  select l.product_code
    from public.inventory_channel_listings l
   where l.channel = p_channel
     and ((nullif(btrim(coalesce(p_item_code,'')),'') is not null
           and l.external_item_code = btrim(p_item_code))
      or (nullif(btrim(coalesce(p_item_url,'')),'') is not null
           and public.inv_norm_url(l.url) = public.inv_norm_url(p_item_url)))
   order by (l.external_item_code = btrim(coalesce(p_item_code,''))) desc nulls last, l.product_code
   limit 1;
$$;

comment on function public.inv_listing_product is
  'モールの商品コード（external_item_code）か掲載URLから商品コードを引く。
   商品コードの一致を優先し、どちらも当たらなければNULL（URLやSKUから推測はしない）。';

-- ------------------------------------------------------------
-- 33-4) 受注を取り込んで在庫を確保する
--
--     p_orders は Edge Function が整えた明細の配列：
--       [{ order_number, line_number, item_code, item_url, qty, price,
--          ordered_at, shipped (boolean), cancelled (boolean), raw }]
--
--     1明細ずつ、数量ぶんだけ個体を確保する。
--       取り込み済み        … 何もしない（冪等）
--       商品が引けない      … status='未割当' で記録して知らせる（在庫は動かさない）
--       在庫が足りない      … status='在庫なし' で記録して知らせる
--       確保できた          … 在庫 → 販売予約（inv_sale_reserve）
--       発送済みで来た      … 続けて 販売予約 → 売却済（＝販売済み）
--       キャンセルで来た    … 確保済みなら 販売予約 → 在庫 に戻す
-- ------------------------------------------------------------
create or replace function public.inv_sale_orders_apply(
  p_orders  jsonb,
  p_channel text default 'rakuten'
) returns jsonb
language plpgsql security invoker set search_path = public as $$
declare
  o            jsonb;
  v_order      text;
  v_line       text;
  v_qty        integer;
  v_unit       integer;
  v_code       text;
  v_item       public.inventory_items;
  v_row        public.inventory_sale_orders;
  v_shipped    boolean;
  v_cancelled  boolean;
  v_new        integer := 0;
  v_already    integer := 0;
  v_reserved   integer := 0;
  v_shippedn   integer := 0;
  v_cancelledn integer := 0;
  v_unmatched  jsonb := '[]'::jsonb;
  v_nostock    jsonb := '[]'::jsonb;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  if p_orders is null or jsonb_typeof(p_orders) <> 'array' then
    raise exception '受注データがありません';
  end if;

  for o in select value from jsonb_array_elements(p_orders) loop
    v_order := nullif(btrim(coalesce(o->>'order_number','')), '');
    v_line  := coalesce(nullif(btrim(coalesce(o->>'line_number','')), ''), '1');
    if v_order is null then
      continue;   -- 注文番号が無いものは冪等にできないので取り込まない
    end if;
    v_qty       := greatest(coalesce((o->>'qty')::integer, 1), 1);
    v_shipped   := coalesce((o->>'shipped')::boolean, false);
    v_cancelled := coalesce((o->>'cancelled')::boolean, false);
    v_code      := public.inv_listing_product(p_channel, o->>'item_code', o->>'item_url');

    for v_unit in 1..v_qty loop
      -- 同じ注文が同時に2回届いても在庫を二重に減らさないため、明細ごとに
      -- 先に鍵をかけてから在庫を確保する。あとから来たほうはここで待たされ、
      -- 下の select で「取り込み済み」を見つけて何もしない。
      -- （鍵を取らずに進めると、両方が在庫を取りにいって、あとから来たほうの
      --   unique 違反でロールバックしたときに確保が巻き戻ってしまう）
      perform pg_advisory_xact_lock(hashtextextended(
        p_channel || '/' || v_order || '/' || v_line || '/' || v_unit::text, 0));

      -- すでに取り込んだ明細か（注文番号×明細番号×連番で見る）
      select * into v_row from public.inventory_sale_orders
       where channel = p_channel and order_number = v_order
         and line_number = v_line and unit_no = v_unit
       for update;

      if found then
        v_already := v_already + 1;
        -- 取り込み済みでも、発送・キャンセルの知らせは進める
        if v_cancelled and v_row.status <> 'キャンセル' then
          if v_row.item_id is not null then
            select * into v_item from public.inventory_items where id = v_row.item_id for update;
            if v_item.status = '販売予約' then
              perform public.inv_item_op(v_row.item_id, '予約解除', null,
                       p_channel || ' 注文 ' || v_order || ' のキャンセル');
            end if;
          end if;
          update public.inventory_sale_orders set status = 'キャンセル' where id = v_row.id;
          v_cancelledn := v_cancelledn + 1;
        elsif v_shipped and v_row.status = '受注' and v_row.item_id is not null then
          select * into v_item from public.inventory_items where id = v_row.item_id for update;
          if v_item.status = '販売予約' then
            perform public.inv_item_op(v_row.item_id, '売却',
                     nullif(v_row.price, null)::text,
                     p_channel || ' 注文 ' || v_order || ' 発送');
          end if;
          update public.inventory_sale_orders set status = '発送済' where id = v_row.id;
          v_shippedn := v_shippedn + 1;
        end if;
        continue;
      end if;

      -- ここから新しい明細
      if v_code is null then
        insert into public.inventory_sale_orders
          (channel, order_number, line_number, unit_no, item_code, item_url, price,
           ordered_at, status, note, raw)
        values (p_channel, v_order, v_line, v_unit, o->>'item_code', o->>'item_url',
                (o->>'price')::numeric, (o->>'ordered_at')::timestamptz, '未割当',
                'モールの商品コード・URLから商品を特定できませんでした', o)
        returning * into v_row;
        v_unmatched := v_unmatched || jsonb_build_object(
          'order_number', v_order, 'line_number', v_line,
          'item_code', o->>'item_code', 'item_url', o->>'item_url');
        v_new := v_new + 1;
        continue;
      end if;

      if v_cancelled then
        -- はじめからキャンセルの明細は、在庫を動かさずに記録だけ残す
        insert into public.inventory_sale_orders
          (channel, order_number, line_number, unit_no, item_code, item_url, product_code,
           price, ordered_at, status, raw)
        values (p_channel, v_order, v_line, v_unit, o->>'item_code', o->>'item_url', v_code,
                (o->>'price')::numeric, (o->>'ordered_at')::timestamptz, 'キャンセル', o);
        v_new := v_new + 1;
        continue;
      end if;

      -- 実在庫の確保。8RENTの予約中・貸出中は status が '在庫' ではないので選ばれない
      begin
        v_item := public.inv_sale_reserve(v_code, p_channel,
                    v_order || '-' || v_line || '-' || v_unit,
                    p_channel || ' 注文 ' || v_order);
      exception when others then
        v_item := null;
      end;

      if v_item.id is null then
        insert into public.inventory_sale_orders
          (channel, order_number, line_number, unit_no, item_code, item_url, product_code,
           price, ordered_at, status, note, raw)
        values (p_channel, v_order, v_line, v_unit, o->>'item_code', o->>'item_url', v_code,
                (o->>'price')::numeric, (o->>'ordered_at')::timestamptz, '在庫なし',
                '確保できる在庫がありませんでした', o);
        v_nostock := v_nostock || jsonb_build_object(
          'order_number', v_order, 'line_number', v_line, 'product_code', v_code);
        v_new := v_new + 1;
        continue;
      end if;

      insert into public.inventory_sale_orders
        (channel, order_number, line_number, unit_no, item_code, item_url, product_code,
         item_id, price, ordered_at, status, raw)
      values (p_channel, v_order, v_line, v_unit, o->>'item_code', o->>'item_url', v_code,
              v_item.id, (o->>'price')::numeric, (o->>'ordered_at')::timestamptz, '受注', o)
      returning * into v_row;
      v_new := v_new + 1;
      v_reserved := v_reserved + 1;

      -- 取り込んだ時点ですでに発送済みなら、そのまま売却済へ進める
      if v_shipped then
        perform public.inv_item_op(v_item.id, '売却', (o->>'price'),
                 p_channel || ' 注文 ' || v_order || ' 発送');
        update public.inventory_sale_orders set status = '発送済' where id = v_row.id;
        v_shippedn := v_shippedn + 1;
      end if;
    end loop;
  end loop;

  return jsonb_build_object(
    'channel', p_channel,
    'new', v_new, 'already', v_already,
    'reserved', v_reserved, 'shipped', v_shippedn, 'cancelled', v_cancelledn,
    'unmatched', v_unmatched, 'no_stock', v_nostock);
end $$;

comment on function public.inv_sale_orders_apply is
  'モールの受注明細を取り込み、在庫を1台ずつ確保する（在庫→販売予約、発送済みなら売却済）。
   注文番号×明細番号×連番で冪等。商品を特定できない明細は在庫を動かさず「未割当」で記録する。
   確保は inv_sale_reserve（inv_reserve_available_item）を通すので、8RENTの申込と同じ1台を
   二重に取ることはない。';

-- ------------------------------------------------------------
-- 33-5) 取り込み後に人が直す（未割当の明細に商品を当てる）
-- ------------------------------------------------------------
create or replace function public.inv_sale_order_link(
  p_id   bigint,
  p_code text
) returns public.inventory_sale_orders
language plpgsql security invoker set search_path = public as $$
declare
  r      public.inventory_sale_orders;
  v_item public.inventory_items;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into r from public.inventory_sale_orders where id = p_id for update;
  if not found then
    raise exception '受注明細が見つかりません（%）', p_id;
  end if;
  if r.item_id is not null then
    raise exception 'この明細にはすでに個体が割り当たっています（%）', r.item_id;
  end if;
  if r.status = 'キャンセル' then
    raise exception 'キャンセル済みの明細です';
  end if;
  if not exists (select 1 from public.inventory_products where code = p_code) then
    raise exception '商品が見つかりません（%）', p_code;
  end if;

  v_item := public.inv_sale_reserve(p_code, r.channel,
              r.order_number || '-' || r.line_number || '-' || r.unit_no,
              r.channel || ' 注文 ' || r.order_number || '（手動で割り当て）');
  if v_item.id is null then
    raise exception 'この商品に確保できる在庫がありません（%）', p_code;
  end if;

  update public.inventory_sale_orders
     set product_code = p_code, item_id = v_item.id, status = '受注',
         note = null
   where id = p_id
  returning * into r;
  return r;
end $$;

comment on function public.inv_sale_order_link is
  '商品を特定できなかった受注明細に、人が商品を当てて在庫を確保する。確保は inv_sale_reserve を通す。';

grant select on public.inventory_sale_orders to authenticated;
grant execute on function public.inv_listing_product(text,text,text) to authenticated;
grant execute on function public.inv_sale_orders_apply(jsonb,text) to authenticated;
grant execute on function public.inv_sale_order_link(bigint,text) to authenticated;

commit;
