-- ============================================================
-- 法人ITまるごと見積（/quote）の受け皿
--   2026-09-21（2026-09-20-master-management.sql の後に流す追補）
--
--   これまで公開側から送れたのは「この機種を借りたい」という
--   商品ありきの申込（inventory_rental_requests）だけだった。
--   商品の表は product_code が必須なので、「20名ぶんのPCと
--   ネットワークとセキュリティを一式」のような、商品が決まっていない
--   相談は受けられない。
--
--   案件（inventory_deals）を作る。/quote から届くのは
--   「用途・人数・台数・期間・希望スペック・付帯作業」だけで、
--   この時点では 決済もしないし、個体も押さえない。
--   スタッフが中身を見て、購入・レンタル・組み合わせを提案する。
--
--   入っているもの
--     inventory_deals            案件（希望受付）
--     inv_deal_create()          公開側から希望を送る（匿名可・security definer）
--     inv_deal_set_status()      社内で状態を進める
--     inv_deal_note()            社内メモを書く
--
--   あとからStripeを足せるようにしておく
--     案件に customer / subscription / invoice のIDを持てる列だけ先に置く。
--     Phase 1 では使わない（NULLのまま）。見積の明細・契約・支払は
--     Phase 2以降に別テーブルとして足す。ここで作り込まない。
--
--   何度流しても同じ結果になる。
--
--   実行後の確認
--     select id, status, purpose, headcount, qty from public.inventory_deals
--      order by created_at desc limit 10;
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 44-1) 案件
--
--     商品は決まっていなくてよい（product_code を持たない）。
--     公開側は「何が要るか」を書くだけで、何をどう用意するかは社内で決める。
--
--     状態は、レンタル申込（inventory_rental_requests）と同じ言葉から始めて、
--     見積・承認・契約まで伸ばしている。Phase 1 で使うのは 希望受付 だけで、
--     先の状態は画面から進められるようにしてある。
-- ------------------------------------------------------------
create table if not exists public.inventory_deals (
  id            bigint generated by default as identity primary key,
  -- どこから届いたか（top / quote / pc など。あとで導線ごとの成果を見るため）
  source        text not null default 'quote',
  status        text not null default '希望受付',

  -- お客様
  company       text,
  customer_name text not null,
  email         text,
  phone         text,

  -- 何に使うか
  purpose       text,                  -- 新入社員 / 短期プロジェクト / オフィス開設 …
  headcount     integer,               -- 人数
  qty           integer,               -- 希望台数
  start_date    date,                  -- 利用開始希望日
  months        integer,               -- 利用期間（月）。買い切り希望なら null

  -- どんなものが要るか。選択肢が増えても表を変えなくてよいよう jsonb で持つ
  --   spec      … cpu / memory / storage / screen / office / webcam / numpad
  --   services  … 初期設定・ネットワーク・セキュリティ・現地設置・研修 …
  --   grade     … budget（コスト重視）/ standard / latest（新品・最新）/ any（おまかせ）
  spec          jsonb not null default '{}'::jsonb,
  services      text[] not null default '{}',
  grade         text,
  message       text,                  -- その他のご希望

  -- 社内
  note          text,                  -- スタッフのメモ
  actor         text,                  -- 最後に動かした人

  -- Stripe（Phase 3で使う。いまは入れない）
  stripe_customer_id     text,
  stripe_subscription_id text,
  stripe_invoice_id      text,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.inventory_deals is
  '法人ITまるごと見積（/quote）から届く案件。商品が決まっていなくても受けられる。
   この時点では決済も個体の確保もしない（status=希望受付）。
   購入・レンタル・組み合わせのどれにするかは、社内で中身を見てから決める。';
comment on column public.inventory_deals.services is
  '希望する付帯作業。初期設定・キッティング・ネットワーク・セキュリティ・現地設置・研修 など。';
comment on column public.inventory_deals.grade is
  'budget（コスト重視・整備済み中心）/ standard / latest（新品・最新）/ any（おまかせ）。
   お客様に新品と中古を最初から選ばせるのではなく、方針だけ伺う。';
comment on column public.inventory_deals.spec is
  '希望スペックの控え（CPU・メモリ・ストレージ・画面・Office・カメラ・テンキー）。
   選択肢が増えても表を変えなくてよいように jsonb で持つ。';
comment on column public.inventory_deals.stripe_customer_id is
  'Phase 3 で使う。Phase 1 では常に NULL。決済はこの表では完結させず、
   請求・継続課金は別テーブル（Phase 3）で持つ。';

create index if not exists inventory_deals_status_idx
  on public.inventory_deals (status, created_at desc);
create index if not exists inventory_deals_created_idx
  on public.inventory_deals (created_at desc);

drop trigger if exists inventory_deals_touch on public.inventory_deals;
create trigger inventory_deals_touch before update on public.inventory_deals
  for each row execute function public.inv_touch();

-- 既存のレンタル申込からも案件をたどれるようにしておく（Phase 2 で使う）
alter table public.inventory_rental_requests
  add column if not exists deal_id bigint references public.inventory_deals(id) on delete set null;

comment on column public.inventory_rental_requests.deal_id is
  'もとになった案件。機種指定の申込と、まるごと見積から始まった案件をつなぐ（Phase 2で使う）。';

-- ------------------------------------------------------------
-- 44-2) 公開側から希望を送る
--
--     匿名（anon）から呼べる唯一の書き込み口。security definer にして、
--     表そのものへの insert 権限は渡さない（列を選んで入れさせないため）。
--     決済もしないし、個体も押さえない。ここでやるのは保存だけ。
-- ------------------------------------------------------------
create or replace function public.inv_deal_create(
  p_name      text,
  p_company   text default null,
  p_email     text default null,
  p_phone     text default null,
  p_purpose   text default null,
  p_headcount integer default null,
  p_qty       integer default null,
  p_start     date default null,
  p_months    integer default null,
  p_grade     text default null,
  p_spec      jsonb default '{}'::jsonb,
  p_services  text[] default '{}',
  p_message   text default null,
  p_source    text default 'quote'
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_id bigint;
begin
  if p_name is null or btrim(p_name) = '' then
    raise exception 'ご担当者名を入力してください';
  end if;
  if coalesce(p_qty, 0) < 0 or coalesce(p_qty, 0) > 5000 then
    raise exception '台数は0〜5000台でお願いします（それ以上はお電話でご相談ください）';
  end if;
  if coalesce(p_headcount, 0) < 0 or coalesce(p_headcount, 0) > 5000 then
    raise exception '人数は0〜5000名でお願いします';
  end if;
  if p_months is not null and (p_months < 0 or p_months > 120) then
    raise exception '利用期間は0〜120ヶ月でお願いします';
  end if;
  if p_grade is not null and p_grade not in ('budget', 'standard', 'latest', 'any') then
    raise exception 'ご希望の方針が正しくありません（%）', p_grade;
  end if;

  insert into public.inventory_deals
    (source, status, company, customer_name, email, phone,
     purpose, headcount, qty, start_date, months, grade, spec, services, message)
  values
    (coalesce(nullif(btrim(coalesce(p_source, '')), ''), 'quote'), '希望受付',
     nullif(btrim(coalesce(p_company, '')), ''), btrim(p_name),
     nullif(btrim(coalesce(p_email, '')), ''), nullif(btrim(coalesce(p_phone, '')), ''),
     nullif(btrim(coalesce(p_purpose, '')), ''), p_headcount, p_qty, p_start, p_months,
     p_grade, coalesce(p_spec, '{}'::jsonb), coalesce(p_services, '{}'),
     nullif(btrim(coalesce(p_message, '')), ''))
  returning id into v_id;

  return jsonb_build_object('deal_id', v_id, 'status', '希望受付');
end $$;

comment on function public.inv_deal_create is
  '法人ITまるごと見積の送信口。匿名から呼べる。保存するだけで、決済も個体の確保もしない。
   在庫が無くても受け付ける（在庫と調達を組み合わせて用意するのが8RENTの仕事なので、
   ここで断らない）。';

-- ------------------------------------------------------------
-- 44-3) 社内で案件を動かす
-- ------------------------------------------------------------
create or replace function public.inv_deal_set_status(
  p_id     bigint,
  p_status text
) returns public.inventory_deals
language plpgsql
security invoker
set search_path = public
as $$
declare r public.inventory_deals;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  if p_status not in ('希望受付', '在庫・調達確認', '見積', '顧客承認', '契約', 'ご縁なし') then
    raise exception '知らない状態です（%）', p_status;
  end if;
  update public.inventory_deals
     set status = p_status, actor = public.inv_actor()
   where id = p_id
  returning * into r;
  if not found then
    raise exception '案件が見つかりません（%）', p_id;
  end if;
  return r;
end $$;

comment on function public.inv_deal_set_status is
  '案件の状態を進める。希望受付 → 在庫・調達確認 → 見積 → 顧客承認 → 契約。
   見積の明細と契約そのものは Phase 2 以降に別テーブルで持つ。';

create or replace function public.inv_deal_note(
  p_id   bigint,
  p_note text
) returns public.inventory_deals
language plpgsql
security invoker
set search_path = public
as $$
declare r public.inventory_deals;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  update public.inventory_deals
     set note = nullif(btrim(coalesce(p_note, '')), ''), actor = public.inv_actor()
   where id = p_id
  returning * into r;
  if not found then
    raise exception '案件が見つかりません（%）', p_id;
  end if;
  return r;
end $$;

comment on function public.inv_deal_note is '案件に社内メモを書く。';

-- ------------------------------------------------------------
-- 44-4) 権限
--
--     案件にはお客様の連絡先が入るので、anon には読ませない。
--     書き込みも表へ直接はさせず、inv_deal_create() だけを開ける。
-- ------------------------------------------------------------
alter table public.inventory_deals enable row level security;

drop policy if exists "inventory_deals read" on public.inventory_deals;
create policy "inventory_deals read" on public.inventory_deals
  for select to authenticated using (true);

drop policy if exists "inventory_deals write" on public.inventory_deals;
create policy "inventory_deals write" on public.inventory_deals
  for update to authenticated
  using (public.inv_can_edit()) with check (public.inv_can_edit());

grant select, update on public.inventory_deals to authenticated;

revoke all on function public.inv_deal_create(text,text,text,text,text,integer,integer,date,integer,text,jsonb,text[],text,text) from public;
grant execute on function public.inv_deal_create(text,text,text,text,text,integer,integer,date,integer,text,jsonb,text[],text,text) to anon, authenticated;
revoke all on function public.inv_deal_set_status(bigint,text) from public;
revoke all on function public.inv_deal_note(bigint,text) from public;
grant execute on function public.inv_deal_set_status(bigint,text) to authenticated;
grant execute on function public.inv_deal_note(bigint,text) to authenticated;

commit;
