-- ============================================================
-- 佐川急便の運賃表（サイズ × 地域）を持つ
--
--   何度流しても同じ結果になる（create table if not exists /
--   on conflict do update / create or replace）。
--
--   このmigrationですること
--     1) inventory_shipping_tariffs（運賃表）を作る
--     2) いただいた陸便・元払の運賃表を **暫定（provisional）** として入れる
--     3) 都道府県 → 地域 の対応を入れる（沖縄は入れない＝要確認）
--     4) 運賃表を入れ替える・切り替える関数を作る
--     5) 配送サイズの検証を、運賃表のサイズに合わせる
--
--   このmigrationがしないこと
--     ・Phase 1 / 1.5 の列と関数は変えない（配送サイズの検証だけ広げる）
--     ・沖縄・離島・着払・即日・夜間割増は**自動計算しない**（要確認にする）
--     ・在庫・出品情報・plan_price は変更しない
--
--   運賃表は**税別**なので、税別運賃・税率・税込送料を分けて持つ。
--   価格計算に使うのは、実際に負担する**税込**の送料。
--
--   ★ この運賃表は過去の契約資料なので rate_status = 'provisional'（暫定）です。
--     現行契約の表が確認できたら inv_shipping_tariff_set() で入れ替え、
--     inv_shipping_tariff_activate() で切り替えます。
--
--   前提：zaiko/migrations/2026-10-06-channel-pricing-rules.sql
-- ============================================================

begin;

do $$
begin
  if not exists (select 1 from information_schema.columns
                  where table_schema = 'public' and table_name = 'inventory_products'
                    and column_name = 'shipping_size') then
    raise exception 'shipping_size 列がありません。先に 2026-10-06-channel-pricing-rules.sql を流してください';
  end if;
end $$;

-- ------------------------------------------------------------
-- 60-1) 運賃表
--
--     1行が「配送会社 × 便 × 支払 × 表の版」1つぶん。
--     現行契約の表が来たら、新しい行として入れて active を切り替える。
--     古い行は消さずに残すので、いつどの表で計算したかを追える。
-- ------------------------------------------------------------
create table if not exists public.inventory_shipping_tariffs (
  id             bigint generated by default as identity primary key,
  carrier        text not null,                  -- sagawa
  service        text not null,                  -- 陸便
  payment        text not null,                  -- 元払
  rate_status    text not null,                  -- provisional（暫定）/ contract（現行契約）
  label          text,
  source_note    text,
  effective_from date,
  tax_rate       numeric not null default 0.10,  -- 運賃は税別なので、税込にするための税率
  active         boolean not null default false,
  sizes          jsonb   not null default '[]'::jsonb,   -- ["60","80",…]
  regions        jsonb   not null default '{}'::jsonb,   -- {"東京":"関東",…}
  rates          jsonb   not null default '{}'::jsonb,   -- {"60":{"関東":560,…},…} 税別
  excluded       jsonb   not null default '{}'::jsonb,   -- 自動計算しないもの（理由つき）
  created_at     timestamptz default now(),
  updated_at     timestamptz default now(),
  unique (carrier, service, payment, rate_status)
);

comment on table public.inventory_shipping_tariffs is
  '配送会社の運賃表。rates は**税別**で、税込は tax_rate から出す。
   rate_status=provisional は過去資料からの暫定で、現行契約が確認できたら差し替える。';

-- 同じ 配送会社×便×支払 で「使う表」は1つだけ
create unique index if not exists inventory_shipping_tariffs_active_idx
  on public.inventory_shipping_tariffs (carrier, service, payment) where active;

drop trigger if exists inventory_shipping_tariffs_touch on public.inventory_shipping_tariffs;
create trigger inventory_shipping_tariffs_touch before update on public.inventory_shipping_tariffs
  for each row execute function public.inv_touch();

alter table public.inventory_shipping_tariffs enable row level security;
drop policy if exists inventory_shipping_tariffs_read on public.inventory_shipping_tariffs;
create policy inventory_shipping_tariffs_read on public.inventory_shipping_tariffs
  for select to authenticated using (public.inv_role() in ('admin','member','viewer'));
grant select on public.inventory_shipping_tariffs to authenticated;

-- ------------------------------------------------------------
-- 60-2) いただいた運賃表を「暫定」として入れる
--
--     過去の契約資料なので rate_status = 'provisional'。
--     すでに同じ行があれば中身は書き換えない（担当者が直したものを消さない）。
-- ------------------------------------------------------------
insert into public.inventory_shipping_tariffs
  (carrier, service, payment, rate_status, label, source_note, tax_rate, active,
   sizes, regions, rates, excluded)
values (
  'sagawa', '陸便', '元払', 'provisional',
  '佐川急便 陸便・元払（暫定）',
  '過去の契約資料（20260924_13132539-000_rikubin_tekiyo.pdf）から取り込み。現行契約の表が確認できたら差し替える。',
  0.10, true,
  '["60","80","100","140","160","170","180","200","220","240","260"]'::jsonb,
  '{"熊本":"南九州","宮崎":"南九州","鹿児島":"南九州","福岡":"北九州","佐賀":"北九州","長崎":"北九州","大分":"北九州","徳島":"四国","香川":"四国","愛媛":"四国","高知":"四国","鳥取":"中国","島根":"中国","岡山":"中国","広島":"中国","山口":"中国","滋賀":"関西","京都":"関西","大阪":"関西","兵庫":"関西","奈良":"関西","和歌山":"関西","富山":"北陸","石川":"北陸","福井":"北陸","岐阜":"東海","静岡":"東海","愛知":"東海","三重":"東海","新潟":"信越","長野":"信越","茨城":"関東","栃木":"関東","群馬":"関東","埼玉":"関東","千葉":"関東","東京":"関東","神奈川":"関東","山梨":"関東","宮城":"南東北","山形":"南東北","福島":"南東北","青森":"北東北","岩手":"北東北","秋田":"北東北","北海道":"北海道"}'::jsonb,
  '{"60":{"南九州":880,"北九州":880,"四国":800,"中国":720,"関西":640,"北陸":560,"東海":560,"信越":560,"関東":560,"南東北":560,"北東北":640,"北海道":880},"80":{"南九州":1080,"北九州":1080,"四国":1000,"中国":920,"関西":840,"北陸":760,"東海":760,"信越":760,"関東":760,"南東北":760,"北東北":840,"北海道":1080},"100":{"南九州":1330,"北九州":1330,"四国":1250,"中国":1170,"関西":1090,"北陸":1010,"東海":1010,"信越":1010,"関東":1010,"南東北":1010,"北東北":1090,"北海道":1330},"140":{"南九州":1670,"北九州":1670,"四国":1590,"中国":1510,"関西":1430,"北陸":1350,"東海":1350,"信越":1350,"関東":1350,"南東北":1350,"北東北":1430,"北海道":1670},"160":{"南九州":2280,"北九州":2280,"四国":2180,"中国":2080,"関西":1980,"北陸":1880,"東海":1880,"信越":1880,"関東":1880,"南東北":1880,"北東北":1980,"北海道":2280},"170":{"南九州":3600,"北九州":3300,"四国":3100,"中国":3100,"関西":2850,"北陸":2850,"東海":2850,"信越":2850,"関東":2200,"南東北":2900,"北東北":3100,"北海道":3600},"180":{"南九州":4000,"北九州":3650,"四国":3400,"中国":3400,"関西":3100,"北陸":3100,"東海":3100,"信越":3100,"関東":2450,"南東北":3200,"北東北":3400,"北海道":4050},"200":{"南九州":5000,"北九州":4550,"四国":4150,"中国":4150,"関西":3800,"北陸":3800,"東海":3800,"信越":3800,"関東":2950,"南東北":3900,"北東北":4150,"北海道":5000},"220":{"南九州":5950,"北九州":5400,"四国":4950,"中国":4950,"関西":4450,"北陸":4450,"東海":4450,"信越":4450,"関東":3450,"南東北":4600,"北東北":4900,"北海道":6350},"240":{"南九州":7900,"北九州":7100,"四国":6450,"中国":6450,"関西":5800,"北陸":5800,"東海":5800,"信越":5800,"関東":4450,"南東北":6000,"北東北":6450,"北海道":7950},"260":{"南九州":9850,"北九州":8800,"四国":8000,"中国":8000,"関西":7150,"北陸":7150,"東海":7150,"信越":7150,"関東":5450,"南東北":7400,"北東北":8000,"北海道":9950}}'::jsonb,
  '{"沖縄":"運賃表に無いので自動計算しません。要確認","離島":"運賃表に無いので自動計算しません。要確認","着払":"正規運賃扱いのため自動計算しません。要確認","即日配送":"割増があるため自動計算しません。要確認","夜間割増":"割増があるため自動計算しません。要確認"}'::jsonb)
on conflict (carrier, service, payment, rate_status) do nothing;

-- ------------------------------------------------------------
-- 60-3) 運賃表を入れ替える
--
--     現行契約の表が来たら、これで入れて activate で切り替える。
--     形がおかしいものは受け取らない（表がずれたまま値段を出さないため）。
-- ------------------------------------------------------------
create or replace function public.inv_shipping_tariff_set(
  p_doc jsonb
) returns public.inventory_shipping_tariffs
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  r public.inventory_shipping_tariffs;
  k text;
  v jsonb;
  sz text;
  n  int;
begin
  if not public.inv_is_admin() then
    raise exception '運賃表は管理者だけが変えられます';
  end if;
  if p_doc is null or jsonb_typeof(p_doc) <> 'object' then
    raise exception '運賃表は { } の形で渡してください';
  end if;
  foreach k in array array['carrier','service','payment','rate_status','sizes','regions','rates'] loop
    if not (p_doc ? k) then raise exception '% がありません', k; end if;
  end loop;
  if (p_doc ->> 'rate_status') not in ('provisional', 'contract') then
    raise exception 'rate_status は provisional か contract です（いまは %）', p_doc ->> 'rate_status';
  end if;
  if p_doc ? 'tax_rate' and ((p_doc ->> 'tax_rate')::numeric < 0 or (p_doc ->> 'tax_rate')::numeric >= 1) then
    raise exception '税率は0以上1未満で入れてください（0.10 で10%%）';
  end if;
  if jsonb_typeof(p_doc -> 'sizes') <> 'array' or jsonb_array_length(p_doc -> 'sizes') = 0 then
    raise exception 'sizes は1つ以上の配列で入れてください';
  end if;

  -- サイズごとに、地域と金額がそろっているか
  n := 0;
  for sz in select jsonb_array_elements_text(p_doc -> 'sizes') loop
    if not (p_doc -> 'rates' ? sz) then
      raise exception 'サイズ % の運賃がありません', sz;
    end if;
    for k, v in select * from jsonb_each(p_doc -> 'rates' -> sz) loop
      if jsonb_typeof(v) <> 'number' or (v)::numeric < 0 then
        raise exception 'サイズ % の % の運賃は0以上の数で入れてください', sz, k;
      end if;
      n := n + 1;
    end loop;
  end loop;
  if n = 0 then raise exception '運賃が1つも入っていません'; end if;

  -- 都道府県 → 地域。行き先の地域が運賃表に無いと、あとで黙って計算できなくなる
  for k, v in select * from jsonb_each(p_doc -> 'regions') loop
    if jsonb_typeof(v) <> 'string' then
      raise exception '都道府県「%」の地域は文字で入れてください', k;
    end if;
    if not (p_doc -> 'rates' -> (p_doc -> 'sizes' ->> 0) ? (v #>> '{}')) then
      raise exception '地域「%」（%）の運賃が表にありません', v #>> '{}', k;
    end if;
  end loop;

  insert into public.inventory_shipping_tariffs
    (carrier, service, payment, rate_status, label, source_note, effective_from,
     tax_rate, sizes, regions, rates, excluded)
  values (
    p_doc ->> 'carrier', p_doc ->> 'service', p_doc ->> 'payment', p_doc ->> 'rate_status',
    p_doc ->> 'label', p_doc ->> 'source_note', (p_doc ->> 'effective_from')::date,
    coalesce((p_doc ->> 'tax_rate')::numeric, 0.10),
    p_doc -> 'sizes', p_doc -> 'regions', p_doc -> 'rates',
    coalesce(p_doc -> 'excluded', '{}'::jsonb))
  on conflict (carrier, service, payment, rate_status) do update
    set label = excluded.label, source_note = excluded.source_note,
        effective_from = excluded.effective_from, tax_rate = excluded.tax_rate,
        sizes = excluded.sizes, regions = excluded.regions,
        rates = excluded.rates, excluded = excluded.excluded
  returning * into r;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'shipping', r.id::text, coalesce(r.label, r.carrier),
          '運賃表を入れた', '—',
          format('%s %s %s（%s）サイズ%s件', r.carrier, r.service, r.payment, r.rate_status,
                 jsonb_array_length(r.sizes)));
  return r;
end $$;

comment on function public.inv_shipping_tariff_set is
  '運賃表を入れる・入れ替える。管理者だけ。表の形が合わないものは受け取らない。
   入れただけでは使われない（inv_shipping_tariff_activate で切り替える）。';

-- ------------------------------------------------------------
-- 60-4) 使う運賃表を切り替える
-- ------------------------------------------------------------
create or replace function public.inv_shipping_tariff_activate(
  p_id bigint
) returns public.inventory_shipping_tariffs
language plpgsql security definer set search_path = public, pg_catalog as $$
declare r public.inventory_shipping_tariffs;
begin
  if not public.inv_is_admin() then
    raise exception '運賃表は管理者だけが変えられます';
  end if;
  select * into r from public.inventory_shipping_tariffs where id = p_id;
  if not found then raise exception '運賃表が見つかりません（%）', p_id; end if;

  update public.inventory_shipping_tariffs set active = false
   where carrier = r.carrier and service = r.service and payment = r.payment and id <> p_id;
  update public.inventory_shipping_tariffs set active = true
   where id = p_id returning * into r;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'shipping', r.id::text, coalesce(r.label, r.carrier),
          '使う運賃表を切り替えた', '—', format('%s（%s）', coalesce(r.label, r.carrier), r.rate_status));
  return r;
end $$;

comment on function public.inv_shipping_tariff_activate is
  'この運賃表を使う、に切り替える。同じ 配送会社×便×支払 のほかの表は使わなくなる。管理者だけ。';

-- ------------------------------------------------------------
-- 60-5) 配送サイズの検証を、運賃表のサイズに合わせる
--
--     運賃表を差し替えるとサイズも変わるので、決め打ちの一覧をやめる。
--     表が無いときだけ、これまでの一覧で受ける。
-- ------------------------------------------------------------
create or replace function public.inv_product_shipping_size_set(
  p_code text,
  p_size text default null
) returns public.inventory_products
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  v_size text := nullif(btrim(coalesce(p_size, '')), '');
  v_ok   jsonb;
  before text;
  r      public.inventory_products;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  if v_size is not null and v_size <> 'custom' then
    select sizes into v_ok from public.inventory_shipping_tariffs
     where carrier = 'sagawa' and active limit 1;
    if v_ok is null then
      v_ok := '["60","80","100","120","140","160","170","180","200"]'::jsonb;
    end if;
    if not (v_ok ? v_size) then
      raise exception '運賃表にない配送サイズです：%（%、または custom）',
        v_size, (select string_agg(x, '/') from jsonb_array_elements_text(v_ok) as t(x));
    end if;
  end if;

  select shipping_size into before from public.inventory_products where code = p_code;
  update public.inventory_products set shipping_size = v_size
   where code = p_code returning * into r;
  if not found then
    raise exception '商品が見つかりません（%）', p_code;
  end if;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'product', p_code, coalesce(nullif(r.name, ''), r.code),
          '配送サイズを決めた', coalesce(before, '未設定'), coalesce(v_size, '未設定'));
  return r;
end $$;

comment on function public.inv_product_shipping_size_set is
  '商品の配送サイズを決める。使える値は、いま使っている運賃表のサイズと custom。
   送料の金額はここでは持たない。在庫も価格も変更しない。';

-- ------------------------------------------------------------
-- 60-6) 権限
-- ------------------------------------------------------------
revoke all on function public.inv_shipping_tariff_set(jsonb) from public, anon;
grant execute on function public.inv_shipping_tariff_set(jsonb) to authenticated;
revoke all on function public.inv_shipping_tariff_activate(bigint) from public, anon;
grant execute on function public.inv_shipping_tariff_activate(bigint) to authenticated;
revoke all on function public.inv_product_shipping_size_set(text, text) from public, anon;
grant execute on function public.inv_product_shipping_size_set(text, text) to authenticated;

commit;

-- 確認用（実行しなくてよい）
--   select carrier, service, payment, rate_status, active, tax_rate,
--          jsonb_array_length(sizes) as サイズ数
--     from public.inventory_shipping_tariffs;
--   -- 関東・100サイズの税別運賃
--   select rates -> '100' ->> '関東' from public.inventory_shipping_tariffs where active;
