-- ============================================================
-- 49) 契約（Phase 3-a）
--
--   承認済みの見積から「契約」を作る。ここでやるのは4つまで。
--     契約を作る → 契約を確定する → 支払条件を確定する → 後払いの社内承認
--
--   Phase 3-a では、まだ次のことはしません。
--     ・在庫の確保（手配）        … Phase 3-c
--     ・請求と入金                … Phase 3-b
--     ・顧客向けの契約確認ページ  … Phase 3-d
--     ・Stripe                    … Phase 3-e
--   この migration は inventory_items を一切変更しませんし、
--   inv_sale_reserve() も inv_rental_allocate() も呼びません。
--
--   いちばん大事な考え方
--     「契約が決まった」「支払い方が決まった」「お金が入った」「モノを押さえた」は
--     4つとも別のことです。1つの列で表しません。
--
--       契約が決まった     status              = 確定
--       支払い方が決まった  terms_confirmed_at  が入る
--       お金が入った       payment_status      = 入金済み
--       モノを押さえた     fulfillment_status  が 手配中 以降
--
--     請求書払いの法人・自治体では、入金は納品のあとになります。
--     「入金されるまで在庫を確保できない」という作りにすると回らないので、
--     手配してよいかは入金ではなく「支払条件＋社内承認」で決めます。
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 49-1) 契約番号
-- ------------------------------------------------------------
create or replace function public.inv_contract_no(p_deal bigint, p_seq integer)
returns text language sql immutable as $$
  select 'C-' || lpad(p_deal::text, 5, '0') || '-' || p_seq::text
$$;

comment on function public.inv_contract_no is '契約番号を組み立てる。C-案件ID-枝番（例 C-00012-1）。';

-- ------------------------------------------------------------
-- 49-2) 契約ヘッダ
--
--     承認済み見積の中身を、ここへ写して固定します（スナップショット）。
--     見積があとから取り消されても、契約の中身は変わりません。
-- ------------------------------------------------------------
create table if not exists public.inventory_contracts (
  id          bigint generated by default as identity primary key,
  deal_id     bigint not null references public.inventory_deals(id) on delete cascade,
  quote_id    bigint references public.inventory_quotes(id) on delete set null,
  seq         integer not null default 1,

  -- 契約そのものの状態。支払い・手配とは別に動く
  status      text not null default '作成中',

  -- 契約時点のお客様（見積・案件から写す）
  company        text,
  customer_name  text,
  email          text,
  phone          text,

  -- 請求先。契約先と違うことがある（自治体・学校法人・親会社一括請求・経理部指定）
  billing_company     text,
  billing_department  text,
  billing_person      text,
  billing_postal_code text,
  billing_address     text,
  billing_email       text,
  billing_note        text,

  title         text,
  contract_date date,
  start_date    date,
  end_date      date,

  -- 支払い方（条件）。「決まったかどうか」は terms_confirmed_at で見る
  payment_method text,                       -- カード / 請求書払い / 銀行振込
  payment_timing text,                       -- 前払い / 後払い
  payment_terms  text,                       -- 月末締め翌月末払い など
  billing_day    integer,                    -- 月額の請求日（1〜31）。Phase 3-b の月次請求で使う
  terms_confirmed_at timestamptz,
  terms_confirmed_by text,

  -- 後払いで「入金前に手配してよい」と決める社内承認。管理者だけができる
  credit_approved_at timestamptz,
  credit_approved_by text,
  credit_note        text,

  -- お金の状態（入金）。契約の状態とは混ぜない
  payment_status     text not null default '未請求',
  -- モノの状態（手配）。明細の集約。契約・支払いとは混ぜない
  fulfillment_status text not null default '未手配',

  -- 見積から写した金額。確定したらもう動かさない
  tax_rate             numeric(5,2) not null default 10,
  initial_total        integer not null default 0,
  monthly_total        integer not null default 0,
  months               integer,
  monthly_period_total integer not null default 0,
  subtotal             integer not null default 0,
  tax                  integer not null default 0,
  total                integer not null default 0,

  -- Stripeは決済手段。契約の主データではないので、参照だけ持つ
  stripe_customer_id     text,
  stripe_subscription_id text,

  note          text,          -- お客様向けの但し書き
  internal_note text,          -- 社内メモ（顧客には出さない）

  confirmed_at timestamptz,
  confirmed_by text,
  actor        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  unique (deal_id, seq),
  constraint inventory_contracts_status_chk check
    (status in ('作成中', '確定', '履行中', '完了', '取消')),
  constraint inventory_contracts_pay_chk check
    (payment_status in ('未請求', '請求済み', '入金待ち', '一部入金', '入金済み', '決済失敗', '取消')),
  constraint inventory_contracts_ful_chk check
    (fulfillment_status in ('未手配', '手配可', '手配中', '準備完了', '発送済み',
                            '貸出中', '完了', '返却待ち', '返却済み')),
  constraint inventory_contracts_method_chk check
    (payment_method is null or payment_method in ('カード', '請求書払い', '銀行振込')),
  constraint inventory_contracts_timing_chk check
    (payment_timing is null or payment_timing in ('前払い', '後払い')),
  constraint inventory_contracts_billing_day_chk check
    (billing_day is null or (billing_day between 1 and 31))
);

comment on table public.inventory_contracts is
  '契約。承認済み見積の中身を写して固定する。
   契約の状態(status)・入金(payment_status)・手配(fulfillment_status)は別々の列で持つ。
   支払条件が決まったかは terms_confirmed_at、後払いの社内承認は credit_approved_at で見る。';

create index if not exists inventory_contracts_deal_idx   on public.inventory_contracts (deal_id);
create index if not exists inventory_contracts_status_idx on public.inventory_contracts (status);

-- ------------------------------------------------------------
-- 49-3) 契約明細
--
--     見積明細をそのまま写します。
--     手配の状態は明細ごとに持ちます。1つの契約の中で
--       PCレンタルは割当済み／モニター販売は一部調達待ち／キッティングは作業待ち
--     が同時に起きるので、ヘッダだけでは表せません。
-- ------------------------------------------------------------
create table if not exists public.inventory_contract_items (
  id           bigint generated by default as identity primary key,
  contract_id  bigint not null references public.inventory_contracts(id) on delete cascade,
  quote_item_id bigint,                     -- どの見積明細から写したか（参照だけ）
  sort_no      integer not null default 0,
  kind         text not null default 'other',
  product_code text references public.inventory_products(code) on delete set null,
  name         text not null,
  spec         text,
  qty          integer not null default 1,
  unit_price   integer not null default 0,
  months       integer,
  billing      text not null default 'one_time',
  taxable      boolean not null default true,
  note         text,
  amount       integer generated always as
    (qty * unit_price * (case when billing = 'monthly' then greatest(coalesce(months, 1), 1) else 1 end)) stored,

  -- 手配（Phase 3-c で動かす。ここでは箱だけ用意する）
  fulfillment_status text not null default '未手配',
  allocated_qty integer not null default 0,   -- 自社在庫で押さえた数
  procure_qty   integer not null default 0,   -- 外部調達が要る数（仮の個体は作らない）

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint inventory_contract_items_kind_chk check
    (kind in ('sale', 'rental', 'setup', 'kitting', 'install', 'network',
              'service_monthly', 'training', 'other')),
  constraint inventory_contract_items_billing_chk check (billing in ('one_time', 'monthly')),
  constraint inventory_contract_items_ful_chk check
    (fulfillment_status in ('手配不要', '未手配', '手配中', '確保済み', '調達待ち',
                            '発送済み', '貸出中', '返却済み', '完了'))
);

comment on table public.inventory_contract_items is
  '契約明細。契約した時点の品名・スペック・単価・数量・期間を固定する。
   手配の状態は明細ごとに持つ（ヘッダの fulfillment_status はこれの集約）。
   allocated_qty は自社在庫で押さえた数、procure_qty は外部調達が要る数。';

create index if not exists inventory_contract_items_contract_idx
  on public.inventory_contract_items (contract_id, sort_no, id);

-- ------------------------------------------------------------
-- 49-4) 合計を計算しなおす（作成中のあいだだけ）
--
--     確定したら、もう触りません。
-- ------------------------------------------------------------
create or replace function public.inv_contract_recalc(p_id bigint)
returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  c public.inventory_contracts;
  v_initial integer; v_monthly integer; v_months integer;
  v_period integer; v_taxable integer; v_subtotal integer;
begin
  select * into c from public.inventory_contracts where id = p_id;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;

  select
    coalesce(sum(case when billing = 'one_time' then amount else 0 end), 0),
    coalesce(sum(case when billing = 'monthly' then qty * unit_price else 0 end), 0),
    max(case when billing = 'monthly' then greatest(coalesce(months, 1), 1) else null end),
    coalesce(sum(case when billing = 'monthly' then amount else 0 end), 0),
    coalesce(sum(case when taxable then amount else 0 end), 0)
    into v_initial, v_monthly, v_months, v_period, v_taxable
    from public.inventory_contract_items where contract_id = p_id;

  v_subtotal := v_initial + v_period;

  update public.inventory_contracts
     set initial_total        = v_initial,
         monthly_total        = v_monthly,
         months               = v_months,
         monthly_period_total = v_period,
         subtotal             = v_subtotal,
         tax                  = round(v_taxable * c.tax_rate / 100)::integer,
         total                = v_subtotal + round(v_taxable * c.tax_rate / 100)::integer,
         updated_at           = now()
   where id = p_id
  returning * into c;
  return c;
end $$;

comment on function public.inv_contract_recalc is
  '契約の合計を明細から計算しなおす。初期費用と月額は分けたまま持つ。確定後は呼ばない。';

-- ------------------------------------------------------------
-- 49-5) 承認済みの見積から契約を作る
--
--     見積の中身を全部写します（スナップショット）。
--     あとで見積が取り消されても、契約はそのままです。
-- ------------------------------------------------------------
create or replace function public.inv_contract_create(p_quote_id bigint)
returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  q   public.inventory_quotes;
  d   public.inventory_deals;
  c   public.inventory_contracts;
  v_seq integer;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;

  select * into q from public.inventory_quotes where id = p_quote_id;
  if not found then raise exception '見積が見つかりません（%）', p_quote_id; end if;
  if q.status <> '承認' then
    raise exception 'お客様が承認した見積からだけ契約を作れます（この見積は「%」）', q.status;
  end if;
  if exists (select 1 from public.inventory_contracts
              where quote_id = p_quote_id and status <> '取消') then
    raise exception 'この見積からはすでに契約を作っています';
  end if;

  select * into d from public.inventory_deals where id = q.deal_id;
  select coalesce(max(seq), 0) + 1 into v_seq
    from public.inventory_contracts where deal_id = q.deal_id;

  insert into public.inventory_contracts (
    deal_id, quote_id, seq, status,
    company, customer_name, email, phone,
    title, contract_date, start_date, end_date, months,
    tax_rate, note, internal_note, actor)
  values (
    q.deal_id, q.id, v_seq, '作成中',
    d.company, d.customer_name, d.email, d.phone,
    coalesce(q.title, d.company || ' 様 ご契約'), current_date, d.start_date,
    case when d.start_date is not null and coalesce(d.months, 0) > 0
         then (d.start_date + (d.months || ' months')::interval)::date else null end,
    d.months, q.tax_rate, q.note, q.internal_note, public.inv_actor())
  returning * into c;

  -- 見積明細をそのまま写す
  insert into public.inventory_contract_items (
    contract_id, quote_item_id, sort_no, kind, product_code, name, spec,
    qty, unit_price, months, billing, taxable, note, fulfillment_status)
  select c.id, i.id, i.sort_no, i.kind, i.product_code, i.name, i.spec,
         i.qty, i.unit_price, i.months, i.billing, i.taxable, i.note,
         -- 在庫を伴わない行は、はじめから「手配不要」
         case when i.kind in ('sale', 'rental') then '未手配' else '手配不要' end
    from public.inventory_quote_items i
   where i.quote_id = q.id
   order by i.sort_no, i.id;

  c := public.inv_contract_recalc(c.id);

  update public.inventory_deals
     set status = '契約', actor = public.inv_actor()
   where id = q.deal_id and status in ('顧客承認', '契約準備');

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '契約作成',
          public.inv_quote_no(q.deal_id, q.rev), '作成中');
  return c;
end $$;

comment on function public.inv_contract_create is
  'お客様が承認した見積から契約を作る。見積の明細・金額・税率・宛先をその場で写して固定するので、
   あとで見積が取り消されても契約は変わらない。在庫はここでは一切動かさない。';

-- ------------------------------------------------------------
-- 49-6) 契約の中身を直す（作成中のあいだだけ）
-- ------------------------------------------------------------
create or replace function public.inv_contract_set(
  p_id        bigint,
  p_title     text default null,
  p_contract_date date default null,
  p_start     date default null,
  p_end       date default null,
  p_method    text default null,
  p_timing    text default null,
  p_terms     text default null,
  p_billing_day integer default null,
  p_note      text default null,
  p_internal  text default null
) returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status not in ('作成中', '確定') then
    raise exception 'この契約は「%」なので直せません', c.status;
  end if;
  -- 確定後に直せるのは支払条件まわりだけ（金額や期間は動かさない）
  if c.status = '確定' and (p_title is not null or p_contract_date is not null
                            or p_start is not null or p_end is not null) then
    raise exception '確定した契約の件名・日付は直せません。取り消してから作り直してください';
  end if;
  if c.terms_confirmed_at is not null
     and (p_method is not null or p_timing is not null or p_terms is not null) then
    raise exception '支払条件はもう確定しています。変えるときは担当者にご確認ください';
  end if;

  update public.inventory_contracts
     set title         = coalesce(nullif(btrim(coalesce(p_title, '')), ''), title),
         contract_date = coalesce(p_contract_date, contract_date),
         start_date    = coalesce(p_start, start_date),
         end_date      = coalesce(p_end, end_date),
         payment_method = coalesce(nullif(btrim(coalesce(p_method, '')), ''), payment_method),
         payment_timing = coalesce(nullif(btrim(coalesce(p_timing, '')), ''), payment_timing),
         payment_terms  = coalesce(nullif(btrim(coalesce(p_terms, '')), ''), payment_terms),
         billing_day    = coalesce(p_billing_day, billing_day),
         note           = coalesce(p_note, note),
         internal_note  = coalesce(p_internal, internal_note),
         actor          = public.inv_actor(),
         updated_at     = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '契約変更', null,
          coalesce(c.payment_method, '支払方法なし')
            || coalesce('／' || c.payment_timing, '') || coalesce('／' || c.payment_terms, ''));
  return c;
end $$;

comment on function public.inv_contract_set is
  '契約の件名・日付・支払条件を直す。確定後は支払条件まわりだけ。
   支払条件を確定したあとは、支払方法・前後払い・支払条件を変えられない。';

-- ------------------------------------------------------------
-- 49-7) 請求先を入れる
--
--     契約先と請求先が違うことがある（自治体・学校法人・親会社一括請求・経理部指定）。
--     請求書を出すときに困らないよう、部署・郵便番号・請求先メールまで持つ。
-- ------------------------------------------------------------
create or replace function public.inv_contract_billing_set(
  p_id         bigint,
  p_company    text default null,
  p_department text default null,
  p_person     text default null,
  p_postal     text default null,
  p_address    text default null,
  p_email      text default null,
  p_note       text default null
) returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status in ('完了', '取消') then
    raise exception 'この契約は「%」なので直せません', c.status;
  end if;

  update public.inventory_contracts
     set billing_company     = nullif(btrim(coalesce(p_company, '')), ''),
         billing_department  = nullif(btrim(coalesce(p_department, '')), ''),
         billing_person      = nullif(btrim(coalesce(p_person, '')), ''),
         billing_postal_code = nullif(btrim(coalesce(p_postal, '')), ''),
         billing_address     = nullif(btrim(coalesce(p_address, '')), ''),
         billing_email       = nullif(btrim(coalesce(p_email, '')), ''),
         billing_note        = nullif(btrim(coalesce(p_note, '')), ''),
         actor = public.inv_actor(), updated_at = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '請求先変更', null,
          coalesce(c.billing_company, '（契約先と同じ）'));
  return c;
end $$;

comment on function public.inv_contract_billing_set is
  '請求先を入れる。空にすれば「契約先と同じ」という意味になる。';

-- ------------------------------------------------------------
-- 49-8) 明細を直す・消す（作成中のあいだだけ）
--
--     基本は見積の写しですが、契約直前の直しは実務で起きるので、
--     作成中のあいだだけ触れるようにしておく。確定したら固定。
-- ------------------------------------------------------------
create or replace function public.inv_contract_item_save(
  p_contract_id bigint,
  p_item_id     bigint default null,
  p_kind        text    default 'other',
  p_name        text    default null,
  p_spec        text    default null,
  p_qty         integer default 1,
  p_unit        integer default 0,
  p_months      integer default null,
  p_billing     text    default null,
  p_taxable     boolean default true,
  p_code        text    default null,
  p_note        text    default null,
  p_sort        integer default null
) returns public.inventory_contract_items
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  c public.inventory_contracts;
  r public.inventory_contract_items;
  v_billing text;
  v_sort    integer;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_contract_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_contract_id; end if;
  if c.status <> '作成中' then
    raise exception 'この契約は「%」なので明細を直せません', c.status;
  end if;
  if nullif(btrim(coalesce(p_name, '')), '') is null then
    raise exception '品名を入れてください';
  end if;

  -- レンタルと月額サービスは月額、それ以外は一括
  v_billing := coalesce(nullif(btrim(coalesce(p_billing, '')), ''),
                        case when p_kind in ('rental', 'service_monthly') then 'monthly' else 'one_time' end);

  if p_item_id is null then
    select coalesce(p_sort, coalesce(max(sort_no), 0) + 10) into v_sort
      from public.inventory_contract_items where contract_id = p_contract_id;
    insert into public.inventory_contract_items
      (contract_id, sort_no, kind, product_code, name, spec, qty, unit_price,
       months, billing, taxable, note, fulfillment_status)
    values (p_contract_id, v_sort, p_kind, nullif(btrim(coalesce(p_code, '')), ''),
            btrim(p_name), nullif(btrim(coalesce(p_spec, '')), ''),
            greatest(coalesce(p_qty, 1), 1), greatest(coalesce(p_unit, 0), 0),
            case when v_billing = 'monthly' then greatest(coalesce(p_months, 1), 1) else p_months end,
            v_billing, coalesce(p_taxable, true), nullif(btrim(coalesce(p_note, '')), ''),
            case when p_kind in ('sale', 'rental') then '未手配' else '手配不要' end)
    returning * into r;
  else
    update public.inventory_contract_items
       set kind = p_kind,
           product_code = nullif(btrim(coalesce(p_code, '')), ''),
           name = btrim(p_name),
           spec = nullif(btrim(coalesce(p_spec, '')), ''),
           qty = greatest(coalesce(p_qty, 1), 1),
           unit_price = greatest(coalesce(p_unit, 0), 0),
           months = case when v_billing = 'monthly' then greatest(coalesce(p_months, 1), 1) else p_months end,
           billing = v_billing,
           taxable = coalesce(p_taxable, true),
           note = nullif(btrim(coalesce(p_note, '')), ''),
           sort_no = coalesce(p_sort, sort_no),
           fulfillment_status = case when p_kind in ('sale', 'rental') then '未手配' else '手配不要' end,
           updated_at = now()
     where id = p_item_id and contract_id = p_contract_id
    returning * into r;
    if not found then raise exception '明細が見つかりません（%）', p_item_id; end if;
  end if;

  perform public.inv_contract_recalc(p_contract_id);
  return r;
end $$;

comment on function public.inv_contract_item_save is
  '契約明細を足す・直す。作成中のあいだだけ。在庫を伴わない種類は「手配不要」にしておく。';

create or replace function public.inv_contract_item_delete(p_contract_id bigint, p_item_id bigint)
returns boolean
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_contract_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_contract_id; end if;
  if c.status <> '作成中' then
    raise exception 'この契約は「%」なので明細を消せません', c.status;
  end if;
  delete from public.inventory_contract_items where id = p_item_id and contract_id = p_contract_id;
  perform public.inv_contract_recalc(p_contract_id);
  return true;
end $$;

comment on function public.inv_contract_item_delete is '契約明細を消す。作成中のあいだだけ。';

-- ------------------------------------------------------------
-- 49-9) 契約を確定する
--
--     ここから先、金額と明細は動かしません。
--     まだ支払条件は決まっていなくてよいし、在庫も押さえません。
-- ------------------------------------------------------------
create or replace function public.inv_contract_confirm(p_id bigint)
returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status <> '作成中' then
    raise exception 'この契約はすでに「%」です', c.status;
  end if;
  if not exists (select 1 from public.inventory_contract_items where contract_id = p_id) then
    raise exception '明細が1行もありません';
  end if;
  if c.contract_date is null then
    raise exception '契約日を入れてください';
  end if;

  update public.inventory_contracts
     set status = '確定', confirmed_at = now(), confirmed_by = public.inv_actor(),
         actor = public.inv_actor(), updated_at = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '契約確定', '作成中',
          '確定（金額 ' || to_char(c.total, 'FM9,999,999,999') || '円・在庫はまだ確保していません）');
  return c;
end $$;

comment on function public.inv_contract_confirm is
  '契約を確定する。ここから明細と金額は動かせない。
   支払条件はまだでよく、在庫も一切確保しない（手配は Phase 3-c の別操作）。';

-- ------------------------------------------------------------
-- 49-10) 支払条件を確定する
--
--     「契約が決まった」とは別のことなので、別の操作にしてあります。
-- ------------------------------------------------------------
create or replace function public.inv_contract_terms_confirm(p_id bigint)
returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status not in ('作成中', '確定') then
    raise exception 'この契約は「%」なので支払条件を確定できません', c.status;
  end if;
  if c.terms_confirmed_at is not null then
    raise exception '支払条件はもう確定しています';
  end if;
  if c.payment_method is null then raise exception '支払方法を選んでください'; end if;
  if c.payment_timing is null then raise exception '前払いか後払いかを選んでください'; end if;
  if nullif(btrim(coalesce(c.payment_terms, '')), '') is null then
    raise exception '支払条件を入れてください（例：月末締め翌月末払い）';
  end if;
  -- 月額があるなら、毎月の請求日が要る（Phase 3-b の月次請求のため）
  if c.monthly_total > 0 and c.billing_day is null then
    raise exception '月額があるので、毎月の請求日を入れてください（1〜31）';
  end if;

  update public.inventory_contracts
     set terms_confirmed_at = now(), terms_confirmed_by = public.inv_actor(),
         actor = public.inv_actor(), updated_at = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '支払条件確定', null,
          c.payment_method || '／' || c.payment_timing || '／' || c.payment_terms);

  update public.inventory_deals
     set status = '支払条件確定', actor = public.inv_actor()
   where id = c.deal_id and status = '契約';
  return c;
end $$;

comment on function public.inv_contract_terms_confirm is
  '支払条件を確定する。契約の確定とは別の操作。ここでも在庫は動かさない。';

-- ------------------------------------------------------------
-- 49-11) 後払いの社内承認（管理者だけ）
--
--     後払い（請求書払い・銀行振込の後払い）は、入金より先に手配します。
--     つまり「入金前にモノを出してよいか」の与信判断なので、
--     ふつうの編集メンバーではなく管理者だけができるようにします。
-- ------------------------------------------------------------
create or replace function public.inv_contract_credit_approve(
  p_id   bigint,
  p_note text default null
) returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_is_admin() then
    raise exception '後払いの社内承認は管理者だけができます';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status <> '確定' then
    raise exception '契約を確定してから承認してください（いまは「%」）', c.status;
  end if;
  if c.terms_confirmed_at is null then
    raise exception '支払条件を確定してから承認してください';
  end if;
  if c.payment_timing <> '後払い' then
    raise exception '後払いの契約だけ承認が要ります（この契約は「%」）', c.payment_timing;
  end if;
  if c.credit_approved_at is not null then
    raise exception 'この契約はもう承認済みです（% ）', c.credit_approved_by;
  end if;

  update public.inventory_contracts
     set credit_approved_at = now(), credit_approved_by = public.inv_actor(),
         credit_note = nullif(btrim(coalesce(p_note, '')), ''),
         actor = public.inv_actor(), updated_at = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '後払い社内承認', null,
          '入金前の手配を承認（' || c.payment_terms || '）'
            || coalesce('／' || c.credit_note, ''));
  return c;
end $$;

comment on function public.inv_contract_credit_approve is
  '後払いの契約について「入金前に手配してよい」と社内で承認する。管理者だけ。
   請求書払い・銀行振込の後払いは、これが与信判断そのものになる。';

-- ------------------------------------------------------------
-- 49-12) 契約を取り消す
-- ------------------------------------------------------------
create or replace function public.inv_contract_cancel(p_id bigint, p_reason text default null)
returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status = '取消' then raise exception 'この契約はすでに取消です'; end if;
  -- 手配が始まっている契約は、個体を戻す必要があるので自動では取り消さない
  if c.fulfillment_status not in ('未手配', '手配可') then
    raise exception 'すでに手配が始まっています（%）。先に個体の手配を戻してください', c.fulfillment_status;
  end if;

  update public.inventory_contracts
     set status = '取消',
         internal_note = coalesce(internal_note || E'\n', '')
           || coalesce('取消：' || nullif(btrim(coalesce(p_reason, '')), ''), '取消'),
         actor = public.inv_actor(), updated_at = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '契約取消', null,
          coalesce(nullif(btrim(coalesce(p_reason, '')), ''), '取消'));
  return c;
end $$;

comment on function public.inv_contract_cancel is
  '契約を取り消す。手配前なら在庫を触っていないので戻す処理は要らない。
   手配が始まっていたら、先に個体の手配を戻す（Phase 3-c）。';

-- ------------------------------------------------------------
-- 49-13) 手配してよいかを判断する（読むだけ。ここでは在庫を動かさない）
--
--     Phase 3-c の［手配に進む］が、この判断をそのまま使います。
--     いま作っておくのは、画面に「なぜまだ押せないか」を出すためです。
--
--       前払い（カード・銀行振込前払い）… 入金済みになってから
--       後払い（請求書払い・銀行振込後払い）… 入金前でも、社内承認があれば手配できる
-- ------------------------------------------------------------
create or replace function public.inv_contract_can_fulfill(p_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = public, pg_catalog as $$
declare c public.inventory_contracts;
begin
  select * into c from public.inventory_contracts where id = p_id;
  if not found then
    return jsonb_build_object('ok', false, 'reason', '契約が見つかりません');
  end if;
  if c.status = '取消' then
    return jsonb_build_object('ok', false, 'reason', 'この契約は取消です');
  end if;
  if c.status = '作成中' then
    return jsonb_build_object('ok', false, 'reason', '契約を確定してください');
  end if;
  if c.terms_confirmed_at is null then
    return jsonb_build_object('ok', false, 'reason', '支払条件を確定してください');
  end if;
  if c.payment_timing = '後払い' and c.credit_approved_at is null then
    return jsonb_build_object('ok', false,
      'reason', '後払いなので、管理者の社内承認が要ります（入金前に手配してよいかの判断です）');
  end if;
  if c.payment_timing = '前払い' and c.payment_status <> '入金済み' then
    return jsonb_build_object('ok', false,
      'reason', '前払いの契約です。入金が確認できてから手配してください（いまは「'
                || c.payment_status || '」）');
  end if;
  return jsonb_build_object('ok', true, 'reason',
    case when c.payment_timing = '後払い'
         then '後払い・社内承認済みなので、入金前でも手配できます'
         else '入金済みなので手配できます' end);
end $$;

comment on function public.inv_contract_can_fulfill is
  '手配してよいかを返す（読むだけ）。前払いは入金済みが条件、後払いは社内承認が条件。
   「入金されるまで手配できない」という作りにしないための入口。Phase 3-c がこれを使う。';

-- ------------------------------------------------------------
-- 49-14) 案件の状態に「支払条件確定」「手配」「完了」を足す
-- ------------------------------------------------------------
create or replace function public.inv_deal_set_status(
  p_id     bigint,
  p_status text
) returns public.inventory_deals
language plpgsql
security invoker
set search_path = public
as $$
declare r public.inventory_deals;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  if p_status not in ('希望受付', '在庫・調達確認', '見積', '顧客承認', '契約準備',
                      '契約', '支払条件確定', '手配', '完了', 'ご縁なし') then
    raise exception '知らない状態です（%）', p_status;
  end if;
  update public.inventory_deals
     set status = p_status, actor = public.inv_actor()
   where id = p_id
  returning * into r;
  if not found then
    raise exception '案件が見つかりません（%）', p_id;
  end if;
  return r;
end $$;

comment on function public.inv_deal_set_status is
  '案件の状態を進める。希望受付 → 在庫・調達確認 → 見積 → 顧客承認 → 契約準備 →
   契約 → 支払条件確定 → 手配 → 完了。
   顧客が見積を承認したときは inv_quote_decide が「契約準備」へ進める。';

-- ------------------------------------------------------------
-- 49-15) 権限
--
--     契約にはお客様の連絡先・請求先・金額が入るので、anon には一切見せない。
--     表は読み取りだけにして、書き込みは関数（security definer）を通す。
--     後払いの社内承認だけは管理者に限る（関数の中で inv_is_admin を見ている）。
-- ------------------------------------------------------------
alter table public.inventory_contracts      enable row level security;
alter table public.inventory_contract_items enable row level security;

drop policy if exists "inventory_contracts read" on public.inventory_contracts;
create policy "inventory_contracts read" on public.inventory_contracts
  for select to authenticated using (true);
drop policy if exists "inventory_contract_items read" on public.inventory_contract_items;
create policy "inventory_contract_items read" on public.inventory_contract_items
  for select to authenticated using (true);

revoke all on public.inventory_contracts      from anon, authenticated;
revoke all on public.inventory_contract_items from anon, authenticated;
grant select on public.inventory_contracts      to authenticated;
grant select on public.inventory_contract_items to authenticated;

revoke all on function public.inv_contract_no(bigint,integer)        from public, anon;
revoke all on function public.inv_contract_recalc(bigint)            from public, anon, authenticated;
revoke all on function public.inv_contract_create(bigint)            from public, anon;
revoke all on function public.inv_contract_set(bigint,text,date,date,date,text,text,text,integer,text,text) from public, anon;
revoke all on function public.inv_contract_billing_set(bigint,text,text,text,text,text,text,text) from public, anon;
revoke all on function public.inv_contract_item_save(bigint,bigint,text,text,text,integer,integer,integer,text,boolean,text,text,integer) from public, anon;
revoke all on function public.inv_contract_item_delete(bigint,bigint) from public, anon;
revoke all on function public.inv_contract_confirm(bigint)           from public, anon;
revoke all on function public.inv_contract_terms_confirm(bigint)     from public, anon;
revoke all on function public.inv_contract_credit_approve(bigint,text) from public, anon;
revoke all on function public.inv_contract_cancel(bigint,text)       from public, anon;
revoke all on function public.inv_contract_can_fulfill(bigint)       from public, anon;

grant execute on function public.inv_contract_no(bigint,integer)        to authenticated, service_role;
grant execute on function public.inv_contract_create(bigint)            to authenticated;
grant execute on function public.inv_contract_set(bigint,text,date,date,date,text,text,text,integer,text,text) to authenticated;
grant execute on function public.inv_contract_billing_set(bigint,text,text,text,text,text,text,text) to authenticated;
grant execute on function public.inv_contract_item_save(bigint,bigint,text,text,text,integer,integer,integer,text,boolean,text,text,integer) to authenticated;
grant execute on function public.inv_contract_item_delete(bigint,bigint) to authenticated;
grant execute on function public.inv_contract_confirm(bigint)           to authenticated;
grant execute on function public.inv_contract_terms_confirm(bigint)     to authenticated;
grant execute on function public.inv_contract_credit_approve(bigint,text) to authenticated;
grant execute on function public.inv_contract_cancel(bigint,text)       to authenticated;
grant execute on function public.inv_contract_can_fulfill(bigint)       to authenticated;

commit;

notify pgrst, 'reload schema';
