-- ============================================================
-- 見積（希望受付 → 見積作成 → 顧客提示 → 顧客承認 → 契約準備）
--   2026-09-22（2026-09-21-sale-catalog.sql の後に流す）
--
--   案件（inventory_deals）1件に、版（rev）を持つ見積をぶら下げます。
--
--   決めていること
--     ・提示済みの見積は編集できない。直すときは複製して新しい版を作る。
--       （提示したあとに金額が変わると、どれが正なのか分からなくなるため）
--     ・新しい版を提示したら、それより前の提示済みの版は自動で失効させる。
--       （お客様が古いURLから承認してしまう事故を防ぐため）
--     ・明細は「そのときの内容」を写して持つ（品名・スペック・単価）。
--       あとから商品マスタが変わっても、出した見積は変わらない。
--     ・販売・レンタル・初期設定費・キッティング費・設置費・ネットワーク費・
--       月額サービス・研修 を、1つの見積に混在できる。
--     ・顧客の［この内容で進める］は契約ではなく意思表示。
--       **この時点で在庫（inventory_items）は一切動かさない。**
--       inv_sale_reserve() も inv_rental_allocate() も呼ばない。
--     ・Stripeはまだ入れない（Phase 3）。
--
--   入っているもの
--     inventory_quotes        見積（案件×版）
--     inventory_quote_items   見積明細
--     inv_quote_totals        合計（初期費用・月額・消費税・税込）
--     inv_quote_create()      案件から見積を作る（前の版の複製も）
--     inv_quote_item_save()   明細の追加・書き換え
--     inv_quote_item_delete() 明細の削除
--     inv_quote_present()     お客様に提示する（tokenを発行し、前の版を失効）
--     inv_quote_cancel()      取消
--     inv_quote_public()      顧客ページが読む（社内メモ・原価は返さない・匿名可）
--     inv_quote_decide()      顧客の［進める］［相談する］（匿名可・在庫は動かさない）
--
--   何度流しても同じ結果になります。
--
--   実行後の確認
--     select id, deal_id, rev, quote_no, status, valid_until from public.inventory_quotes;
--     select * from public.inv_quote_totals;
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 46-1) 見積（案件 × 版）
-- ------------------------------------------------------------
create table if not exists public.inventory_quotes (
  id            bigint generated by default as identity primary key,
  deal_id       bigint not null references public.inventory_deals(id) on delete cascade,
  rev           integer not null default 1,
  status        text not null default '作成中',
  title         text,

  -- 有効期限。既定は提示した日から14日（提示のときに入れる）
  valid_until   date,
  tax_rate      numeric(5,2) not null default 10,

  note          text,          -- お客様向けの但し書き
  internal_note text,          -- 社内メモ（顧客ページには絶対に出さない）

  -- 顧客ページのURLの鍵。提示のときに作る
  token            text unique,
  token_expires_at timestamptz,

  presented_at  timestamptz,
  decided_at    timestamptz,
  decided_by    text,          -- お客様が入力したお名前
  customer_message text,       -- ［内容について相談する］で書かれた内容

  actor         text,          -- 最後に動かした社内の人
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  unique (deal_id, rev)
);

comment on table public.inventory_quotes is
  '案件に対する見積。版（rev）を持ち、提示済みの版は編集しない（直すときは複製して新しい版を作る）。
   新しい版を提示すると、前の提示済みの版は自動で失効する。';
comment on column public.inventory_quotes.status is
  '作成中 / 提示済み / 承認 / 相談中 / 失効 / 取消。顧客が動かせるのは 承認 と 相談中 だけ。';
comment on column public.inventory_quotes.token is
  '顧客ページ（/q/:token）の鍵。提示のときに作る。推測できない長さにする。';
comment on column public.inventory_quotes.internal_note is
  '社内メモ。inv_quote_public() は返さないので、顧客ページには出ない。';

alter table public.inventory_quotes drop constraint if exists inventory_quotes_status_chk;
alter table public.inventory_quotes add constraint inventory_quotes_status_chk
  check (status in ('作成中', '提示済み', '承認', '相談中', '失効', '取消'));
alter table public.inventory_quotes drop constraint if exists inventory_quotes_tax_chk;
alter table public.inventory_quotes add constraint inventory_quotes_tax_chk
  check (tax_rate >= 0 and tax_rate <= 30);

create index if not exists inventory_quotes_deal_idx on public.inventory_quotes (deal_id, rev desc);
create index if not exists inventory_quotes_status_idx on public.inventory_quotes (status, created_at desc);

drop trigger if exists inventory_quotes_touch on public.inventory_quotes;
create trigger inventory_quotes_touch before update on public.inventory_quotes
  for each row execute function public.inv_touch();

-- 見積番号は Q-案件ID-版（画面と顧客ページで同じものを出す）
create or replace function public.inv_quote_no(p_deal bigint, p_rev integer)
returns text language sql immutable as $$
  select 'Q-' || lpad(p_deal::text, 5, '0') || '-' || p_rev::text
$$;

-- ------------------------------------------------------------
-- 46-2) 見積明細
--
--     kind（明細の種類）
--       sale            販売（機器）        一括
--       rental          レンタル（機器）    月額
--       setup           初期設定費          一括
--       kitting         キッティング費      一括
--       install         現地設置・配線費    一括
--       network         ネットワーク構築費  一括
--       service_monthly 月額サービス        月額
--       training        AI研修・Office研修  一括
--       other           その他              一括
--
--     金額は amount（生成列）。月額は 単価 × 数量 × 月数。
--     品名・スペック・単価は「そのときの内容」を写して持つ（スナップショット）。
-- ------------------------------------------------------------
create table if not exists public.inventory_quote_items (
  id           bigint generated by default as identity primary key,
  quote_id     bigint not null references public.inventory_quotes(id) on delete cascade,
  sort_no      integer not null default 0,
  kind         text not null default 'other',
  product_code text references public.inventory_products(code) on delete set null,
  name         text not null,
  spec         text,
  qty          integer not null default 1,
  unit_price   integer not null default 0,
  months       integer,
  billing      text not null default 'one_time',
  taxable      boolean not null default true,
  note         text,
  amount       integer generated always as
    (qty * unit_price * (case when billing = 'monthly' then greatest(coalesce(months, 1), 1) else 1 end)) stored,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.inventory_quote_items is
  '見積の明細。販売・レンタル・設定費・設置費・月額サービス・研修を1つの見積に混在できる。
   品名・スペック・単価はそのときの内容を写して持つので、あとから商品マスタが変わっても見積は変わらない。';
comment on column public.inventory_quote_items.amount is
  '金額（税抜）。一括は 単価×数量、月額は 単価×数量×月数。';

alter table public.inventory_quote_items drop constraint if exists inventory_quote_items_kind_chk;
alter table public.inventory_quote_items add constraint inventory_quote_items_kind_chk
  check (kind in ('sale','rental','setup','kitting','install','network','service_monthly','training','other'));
alter table public.inventory_quote_items drop constraint if exists inventory_quote_items_billing_chk;
alter table public.inventory_quote_items add constraint inventory_quote_items_billing_chk
  check (billing in ('one_time','monthly'));
alter table public.inventory_quote_items drop constraint if exists inventory_quote_items_qty_chk;
alter table public.inventory_quote_items add constraint inventory_quote_items_qty_chk
  check (qty > 0 and qty <= 100000 and unit_price >= 0 and unit_price <= 1000000000
         and (months is null or (months >= 0 and months <= 120)));

create index if not exists inventory_quote_items_quote_idx on public.inventory_quote_items (quote_id, sort_no, id);

drop trigger if exists inventory_quote_items_touch on public.inventory_quote_items;
create trigger inventory_quote_items_touch before update on public.inventory_quote_items
  for each row execute function public.inv_touch();

-- ------------------------------------------------------------
-- 46-3) 合計
--
--     お客様には「初期費用」と「月額費用」を分けて見せる。
--     総額だけ出すと、月額の契約が総額に埋もれてしまうため。
-- ------------------------------------------------------------
drop view if exists public.inv_quote_totals;
create view public.inv_quote_totals as
select
  q.id as quote_id,
  q.deal_id,
  coalesce(sum(i.amount) filter (where i.billing = 'one_time'), 0)::bigint          as initial_total,
  coalesce(sum(i.qty * i.unit_price) filter (where i.billing = 'monthly'), 0)::bigint as monthly_total,
  max(i.months) filter (where i.billing = 'monthly')                                 as months,
  coalesce(sum(i.amount) filter (where i.billing = 'monthly'), 0)::bigint           as monthly_period_total,
  coalesce(sum(i.amount), 0)::bigint                                                 as subtotal,
  round(coalesce(sum(i.amount) filter (where i.taxable), 0) * q.tax_rate / 100)::bigint as tax,
  (coalesce(sum(i.amount), 0)
   + round(coalesce(sum(i.amount) filter (where i.taxable), 0) * q.tax_rate / 100))::bigint as total,
  count(i.id)::integer as line_count
from public.inventory_quotes q
left join public.inventory_quote_items i on i.quote_id = q.id
group by q.id, q.deal_id, q.tax_rate;

comment on view public.inv_quote_totals is
  '見積の合計。initial_total（初期費用・税抜）と monthly_total（月額・税抜）を分けて持ち、
   monthly_period_total は月額×期間。subtotal＝小計、tax＝消費税、total＝税込総額。';

commit;

begin;

-- ------------------------------------------------------------
-- 46-4) 社内の操作
-- ------------------------------------------------------------

/* 見積を作る。p_from があれば、その版の明細を写して新しい版にする（複製） */
create or replace function public.inv_quote_create(
  p_deal_id bigint,
  p_title   text default null,
  p_from    bigint default null
) returns public.inventory_quotes
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  q     public.inventory_quotes;
  v_rev integer;
  src   public.inventory_quotes;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  if not exists (select 1 from public.inventory_deals where id = p_deal_id) then
    raise exception '案件が見つかりません（%）', p_deal_id;
  end if;

  select coalesce(max(rev), 0) + 1 into v_rev from public.inventory_quotes where deal_id = p_deal_id;

  insert into public.inventory_quotes (deal_id, rev, status, title, tax_rate, actor)
  values (p_deal_id, v_rev, '作成中',
          nullif(btrim(coalesce(p_title, '')), ''),
          10, public.inv_actor())
  returning * into q;

  if p_from is not null then
    select * into src from public.inventory_quotes where id = p_from and deal_id = p_deal_id;
    if not found then
      raise exception '複製元の見積が見つかりません（%）', p_from;
    end if;
    update public.inventory_quotes
       set title = coalesce(q.title, src.title), tax_rate = src.tax_rate,
           note = src.note, internal_note = src.internal_note
     where id = q.id
    returning * into q;
    insert into public.inventory_quote_items
      (quote_id, sort_no, kind, product_code, name, spec, qty, unit_price, months, billing, taxable, note)
    select q.id, sort_no, kind, product_code, name, spec, qty, unit_price, months, billing, taxable, note
      from public.inventory_quote_items where quote_id = src.id;
  end if;

  insert into public.inventory_transactions (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'quote', q.id::text,
          public.inv_quote_no(q.deal_id, q.rev), '見積作成',
          case when p_from is null then null else '複製元 ' || p_from::text end, '作成中');
  return q;
end $$;

comment on function public.inv_quote_create is
  '案件に見積を1つ作る。版は自動で増える。p_from を渡すと、その版の明細を写して新しい版にする
   （提示済みの見積は直せないので、直したいときはこれで新しい版を作る）。';

/* 見積のヘッダを直す。提示済み以降は直せない */
create or replace function public.inv_quote_set(
  p_id       bigint,
  p_title    text default null,
  p_valid    date default null,
  p_tax      numeric default null,
  p_note     text default null,
  p_internal text default null
) returns public.inventory_quotes
language plpgsql security definer set search_path = public, pg_catalog as $$
declare q public.inventory_quotes;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into q from public.inventory_quotes where id = p_id for update;
  if not found then raise exception '見積が見つかりません（%）', p_id; end if;
  if q.status <> '作成中' then
    raise exception 'この見積は「%」なので直せません。複製して新しい版を作ってください', q.status;
  end if;
  update public.inventory_quotes
     set title = nullif(btrim(coalesce(p_title, '')), ''),
         valid_until = p_valid,
         tax_rate = coalesce(p_tax, q.tax_rate),
         note = nullif(btrim(coalesce(p_note, '')), ''),
         internal_note = nullif(btrim(coalesce(p_internal, '')), ''),
         actor = public.inv_actor()
   where id = p_id
  returning * into q;
  return q;
end $$;

comment on function public.inv_quote_set is '見積の件名・有効期限・税率・但し書き・社内メモを直す。作成中のときだけ。';

/* 明細の追加・書き換え。p_item_id が null なら追加 */
create or replace function public.inv_quote_item_save(
  p_quote_id  bigint,
  p_item_id   bigint default null,
  p_kind      text default 'other',
  p_name      text default null,
  p_spec      text default null,
  p_qty       integer default 1,
  p_unit      integer default 0,
  p_months    integer default null,
  p_billing   text default null,
  p_taxable   boolean default true,
  p_code      text default null,
  p_note      text default null,
  p_sort      integer default null
) returns public.inventory_quote_items
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  q   public.inventory_quotes;
  r   public.inventory_quote_items;
  v_billing text;
  v_sort integer;
  v_code text;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into q from public.inventory_quotes where id = p_quote_id for update;
  if not found then raise exception '見積が見つかりません（%）', p_quote_id; end if;
  if q.status <> '作成中' then
    raise exception 'この見積は「%」なので直せません。複製して新しい版を作ってください', q.status;
  end if;
  if nullif(btrim(coalesce(p_name, '')), '') is null then
    raise exception '品名を入れてください';
  end if;

  -- 課金のしかたは種類から決める（レンタルと月額サービスだけ月額）
  v_billing := coalesce(nullif(btrim(coalesce(p_billing, '')), ''),
                        case when p_kind in ('rental', 'service_monthly') then 'monthly' else 'one_time' end);
  -- 知らない商品コードは付けない（見積そのものは作れるようにする）
  v_code := nullif(btrim(coalesce(p_code, '')), '');
  if v_code is not null and not exists (select 1 from public.inventory_products where code = v_code) then
    v_code := null;
  end if;

  if p_item_id is null then
    select coalesce(max(sort_no), 0) + 10 into v_sort from public.inventory_quote_items where quote_id = p_quote_id;
    insert into public.inventory_quote_items
      (quote_id, sort_no, kind, product_code, name, spec, qty, unit_price, months, billing, taxable, note)
    values (p_quote_id, coalesce(p_sort, v_sort), p_kind, v_code, btrim(p_name),
            nullif(btrim(coalesce(p_spec, '')), ''), greatest(coalesce(p_qty, 1), 1),
            greatest(coalesce(p_unit, 0), 0), p_months, v_billing, coalesce(p_taxable, true),
            nullif(btrim(coalesce(p_note, '')), ''))
    returning * into r;
  else
    update public.inventory_quote_items
       set kind = p_kind, product_code = v_code, name = btrim(p_name),
           spec = nullif(btrim(coalesce(p_spec, '')), ''),
           qty = greatest(coalesce(p_qty, 1), 1), unit_price = greatest(coalesce(p_unit, 0), 0),
           months = p_months, billing = v_billing, taxable = coalesce(p_taxable, true),
           note = nullif(btrim(coalesce(p_note, '')), ''),
           sort_no = coalesce(p_sort, sort_no)
     where id = p_item_id and quote_id = p_quote_id
    returning * into r;
    if not found then raise exception '明細が見つかりません（%）', p_item_id; end if;
  end if;
  return r;
end $$;

comment on function public.inv_quote_item_save is
  '見積明細の追加・書き換え。作成中のときだけ。レンタルと月額サービスは自動で月額扱いにする。';

create or replace function public.inv_quote_item_delete(p_quote_id bigint, p_item_id bigint)
returns integer
language plpgsql security definer set search_path = public, pg_catalog as $$
declare q public.inventory_quotes; n integer;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into q from public.inventory_quotes where id = p_quote_id for update;
  if not found then raise exception '見積が見つかりません（%）', p_quote_id; end if;
  if q.status <> '作成中' then
    raise exception 'この見積は「%」なので直せません', q.status;
  end if;
  delete from public.inventory_quote_items where id = p_item_id and quote_id = p_quote_id;
  get diagnostics n = row_count;
  return n;
end $$;

comment on function public.inv_quote_item_delete is '見積明細を消す。作成中のときだけ。';

/* お客様に提示する。
   ・tokenを発行して顧客ページを開けるようにする
   ・前に提示した版は、その場で失効させる（古いURLから承認されないように）
   ・案件の状態を「見積」へ進める */
create or replace function public.inv_quote_present(
  p_id    bigint,
  p_days  integer default 14
) returns public.inventory_quotes
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  q       public.inventory_quotes;
  v_token text;
  v_days  integer := greatest(coalesce(p_days, 14), 1);
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into q from public.inventory_quotes where id = p_id for update;
  if not found then raise exception '見積が見つかりません（%）', p_id; end if;
  if q.status <> '作成中' then
    raise exception 'この見積はすでに「%」です。直すときは複製して新しい版を作ってください', q.status;
  end if;
  if not exists (select 1 from public.inventory_quote_items where quote_id = p_id) then
    raise exception '明細が1行もありません。金額を入れてから提示してください';
  end if;

  -- 推測できない鍵。32文字以上になるよう、UUIDを2つつなげて記号を落とす
  v_token := replace(gen_random_uuid()::text, '-', '') || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8);

  -- 先に、同じ案件で前に提示した版を失効させる
  update public.inventory_quotes
     set status = '失効', actor = public.inv_actor()
   where deal_id = q.deal_id and id <> q.id and status in ('提示済み', '相談中');

  update public.inventory_quotes
     set status = '提示済み',
         token = v_token,
         valid_until = coalesce(q.valid_until, (current_date + v_days)),
         token_expires_at = ((coalesce(q.valid_until, (current_date + v_days)) + 30)::timestamptz + interval '1 day' - interval '1 second'),
         presented_at = now(),
         actor = public.inv_actor()
   where id = p_id
  returning * into q;

  -- 案件は「見積」へ
  update public.inventory_deals
     set status = '見積', actor = public.inv_actor()
   where id = q.deal_id and status in ('希望受付', '在庫・調達確認');

  insert into public.inventory_transactions (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'quote', q.id::text, public.inv_quote_no(q.deal_id, q.rev),
          '見積提示', '作成中', '提示済み（有効期限 ' || q.valid_until::text || '）');
  return q;
end $$;

comment on function public.inv_quote_present is
  'お客様に見積を提示する。顧客ページの鍵（token）を作り、同じ案件で前に提示した版は失効させる。
   有効期限は既定14日、顧客ページはその30日後まで開ける（期限を過ぎたら承認ボタンは出さない）。';

create or replace function public.inv_quote_cancel(p_id bigint, p_reason text default null)
returns public.inventory_quotes
language plpgsql security definer set search_path = public, pg_catalog as $$
declare q public.inventory_quotes;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  update public.inventory_quotes
     set status = '取消', actor = public.inv_actor(),
         internal_note = coalesce(internal_note || E'\n', '') || coalesce('取消：' || nullif(btrim(coalesce(p_reason,'')), ''), '取消')
   where id = p_id
  returning * into q;
  if not found then raise exception '見積が見つかりません（%）', p_id; end if;
  insert into public.inventory_transactions (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'quote', q.id::text, public.inv_quote_no(q.deal_id, q.rev), '見積取消', null, '取消');
  return q;
end $$;

comment on function public.inv_quote_cancel is '見積を取り消す。顧客ページは開けなくなる。';

-- ------------------------------------------------------------
-- 46-5) 顧客ページ（匿名で呼べるのはこの2つだけ）
-- ------------------------------------------------------------

/* 顧客ページが読む見積。
   社内メモ・原価・在庫数・管理番号・シリアルは返さない。
   期限切れ・失効・取消でも「なぜ見られないか」を伝えるために、最低限は返す。 */
create or replace function public.inv_quote_public(p_token text)
returns jsonb
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  q     public.inventory_quotes;
  d     public.inventory_deals;
  t     public.inv_quote_totals;
  v_new public.inventory_quotes;
  v_items jsonb;
begin
  if p_token is null or length(btrim(p_token)) < 20 then
    return jsonb_build_object('found', false);
  end if;
  select * into q from public.inventory_quotes where token = btrim(p_token);
  if not found then
    return jsonb_build_object('found', false);
  end if;
  if q.token_expires_at is not null and now() > q.token_expires_at then
    return jsonb_build_object('found', true, 'viewable', false, 'reason', 'token_expired');
  end if;

  select * into d from public.inventory_deals where id = q.deal_id;
  select * into t from public.inv_quote_totals where quote_id = q.id;

  -- もっと新しい提示済みの版があるかどうか（古いURLを開いた人に知らせる）
  select * into v_new from public.inventory_quotes
   where deal_id = q.deal_id and rev > q.rev and status in ('提示済み', '相談中', '承認')
   order by rev desc limit 1;

  select coalesce(jsonb_agg(jsonb_build_object(
           'kind', i.kind, 'name', i.name, 'spec', i.spec,
           'qty', i.qty, 'unit_price', i.unit_price, 'months', i.months,
           'billing', i.billing, 'taxable', i.taxable, 'amount', i.amount, 'note', i.note
         ) order by i.sort_no, i.id), '[]'::jsonb)
    into v_items
    from public.inventory_quote_items i where i.quote_id = q.id;

  return jsonb_build_object(
    'found', true,
    'viewable', true,
    'quote_no', public.inv_quote_no(q.deal_id, q.rev),
    'rev', q.rev,
    'status', q.status,
    'title', q.title,
    'company', d.company,
    'customer_name', d.customer_name,
    'valid_until', q.valid_until,
    'expired', (q.valid_until is not null and current_date > q.valid_until),
    'decidable', (q.status = '提示済み'
                  and (q.valid_until is null or current_date <= q.valid_until)),
    'newer_exists', (v_new.id is not null),
    'tax_rate', q.tax_rate,
    'note', q.note,
    'items', v_items,
    'totals', jsonb_build_object(
      'initial_total', coalesce(t.initial_total, 0),
      'monthly_total', coalesce(t.monthly_total, 0),
      'months', t.months,
      'monthly_period_total', coalesce(t.monthly_period_total, 0),
      'subtotal', coalesce(t.subtotal, 0),
      'tax', coalesce(t.tax, 0),
      'total', coalesce(t.total, 0)),
    'decided_at', q.decided_at,
    'presented_at', q.presented_at
  );
end $$;

comment on function public.inv_quote_public is
  '顧客ページ（/q/:token）が読む見積。社内メモ・原価・在庫数・管理番号は返さない。
   期限切れ・失効・取消のときは decidable=false で返し、ボタンを出さないようにする。';

/* お客様の［この内容で進める］［内容について相談する］。
   進める＝契約ではなく意思表示。**ここでは在庫を一切動かさない。**
   inv_sale_reserve も inv_rental_allocate も呼ばない（手配は契約と支払いが決まってから）。 */
create or replace function public.inv_quote_decide(
  p_token   text,
  p_action  text,
  p_name    text default null,
  p_company text default null,
  p_message text default null
) returns jsonb
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  q public.inventory_quotes;
  v_name text;
begin
  if p_action not in ('approve', 'consult') then
    raise exception '知らない操作です';
  end if;
  v_name := nullif(btrim(coalesce(p_name, '')), '');
  if v_name is null then
    raise exception 'お名前を入力してください';
  end if;

  select * into q from public.inventory_quotes where token = btrim(coalesce(p_token, '')) for update;
  if not found then
    raise exception 'この見積は見つかりません。担当者へお問い合わせください';
  end if;
  if q.status <> '提示済み' then
    raise exception 'この見積は現在お手続きいただけません（%）。担当者へお問い合わせください', q.status;
  end if;
  if q.valid_until is not null and current_date > q.valid_until then
    raise exception 'この見積は有効期限を過ぎています。担当者へお問い合わせください';
  end if;

  if p_action = 'approve' then
    update public.inventory_quotes
       set status = '承認', decided_at = now(), decided_by = v_name
     where id = q.id returning * into q;
    -- 案件は 顧客承認 → 契約準備 へ。ここでも在庫は動かさない
    update public.inventory_deals
       set status = '契約準備', actor = coalesce(actor, 'お客様')
     where id = q.deal_id;
    insert into public.inventory_transactions (actor, ref_kind, ref_id, label, action, before_value, after_value)
    values (v_name || '（お客様）', 'quote', q.id::text, public.inv_quote_no(q.deal_id, q.rev),
            '見積承認', '提示済み', '承認（契約準備へ。在庫は確保していません）');
  else
    update public.inventory_quotes
       set status = '相談中', decided_at = now(), decided_by = v_name,
           customer_message = nullif(btrim(coalesce(p_message, '')), '')
     where id = q.id returning * into q;
    insert into public.inventory_transactions (actor, ref_kind, ref_id, label, action, before_value, after_value)
    values (v_name || '（お客様）', 'quote', q.id::text, public.inv_quote_no(q.deal_id, q.rev),
            '見積の相談', '提示済み', '相談中');
  end if;

  if nullif(btrim(coalesce(p_company, '')), '') is not null then
    update public.inventory_deals
       set company = coalesce(company, btrim(p_company))
     where id = q.deal_id;
  end if;

  return jsonb_build_object('ok', true, 'status', q.status,
                            'quote_no', public.inv_quote_no(q.deal_id, q.rev));
end $$;

comment on function public.inv_quote_decide is
  'お客様の［この内容で進める］［内容について相談する］。進めるは契約ではなく意思表示で、
   案件は「契約準備」へ進む。**この関数は inventory_items を一切変更しない**
   （在庫の確保は、契約と支払方法が決まってから別途行う）。';

-- ------------------------------------------------------------
-- 46-6) 権限
--
--     見積にはお客様の連絡先と金額が入るので、anon には表を読ませない。
--     匿名から呼べるのは inv_quote_public と inv_quote_decide だけ。
-- ------------------------------------------------------------
alter table public.inventory_quotes enable row level security;
alter table public.inventory_quote_items enable row level security;

drop policy if exists "inventory_quotes read" on public.inventory_quotes;
create policy "inventory_quotes read" on public.inventory_quotes
  for select to authenticated using (true);
drop policy if exists "inventory_quote_items read" on public.inventory_quote_items;
create policy "inventory_quote_items read" on public.inventory_quote_items
  for select to authenticated using (true);

revoke insert, update, delete on public.inventory_quotes from authenticated;
revoke insert, update, delete on public.inventory_quote_items from authenticated;
grant select on public.inventory_quotes to authenticated;
grant select on public.inventory_quote_items to authenticated;
grant select on public.inv_quote_totals to authenticated;

revoke all on function public.inv_quote_create(bigint,text,bigint) from public;
revoke all on function public.inv_quote_set(bigint,text,date,numeric,text,text) from public;
revoke all on function public.inv_quote_item_save(bigint,bigint,text,text,text,integer,integer,integer,text,boolean,text,text,integer) from public;
revoke all on function public.inv_quote_item_delete(bigint,bigint) from public;
revoke all on function public.inv_quote_present(bigint,integer) from public;
revoke all on function public.inv_quote_cancel(bigint,text) from public;
grant execute on function public.inv_quote_create(bigint,text,bigint) to authenticated;
grant execute on function public.inv_quote_set(bigint,text,date,numeric,text,text) to authenticated;
grant execute on function public.inv_quote_item_save(bigint,bigint,text,text,text,integer,integer,integer,text,boolean,text,text,integer) to authenticated;
grant execute on function public.inv_quote_item_delete(bigint,bigint) to authenticated;
grant execute on function public.inv_quote_present(bigint,integer) to authenticated;
grant execute on function public.inv_quote_cancel(bigint,text) to authenticated;

revoke all on function public.inv_quote_public(text) from public;
revoke all on function public.inv_quote_decide(text,text,text,text,text) from public;
grant execute on function public.inv_quote_public(text) to anon, authenticated;
grant execute on function public.inv_quote_decide(text,text,text,text,text) to anon, authenticated;
grant execute on function public.inv_quote_no(bigint,integer) to anon, authenticated;


-- ------------------------------------------------------------
-- 46-7) 案件の状態に「契約準備」を足す
--
--     顧客が見積を承認すると、案件は 顧客承認 → 契約準備 へ進む。
--     社内の画面からも同じ状態へ動かせるように、許可する言葉を増やす。
--     （在庫の確保は、契約と支払方法が決まってから。ここでは動かさない）
-- ------------------------------------------------------------
create or replace function public.inv_deal_set_status(
  p_id     bigint,
  p_status text
) returns public.inventory_deals
language plpgsql
security invoker
set search_path = public
as $$
declare r public.inventory_deals;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  if p_status not in ('希望受付', '在庫・調達確認', '見積', '顧客承認', '契約準備', '契約', 'ご縁なし') then
    raise exception '知らない状態です（%）', p_status;
  end if;
  update public.inventory_deals
     set status = p_status, actor = public.inv_actor()
   where id = p_id
  returning * into r;
  if not found then
    raise exception '案件が見つかりません（%）', p_id;
  end if;
  return r;
end $$;

comment on function public.inv_deal_set_status is
  '案件の状態を進める。希望受付 → 在庫・調達確認 → 見積 → 顧客承認 → 契約準備 → 契約。
   顧客が見積を承認したときは inv_quote_decide が「契約準備」へ進める。';

commit;
