-- ============================================================
-- 51) 手配・在庫確保・調達待ち（Phase 3-c）
--
--   担当者が /zaiko/contracts/:id で［手配に進む］を押したときだけ、
--   契約明細に応じて実在庫を確保する。
--
--     契約確定 ＋ 支払条件確定 ＋ 手配条件を満たす
--       → ［手配に進む］
--          販売    → 販売予約
--          レンタル → レンタル申込 → 個体割当
--       → 足りないぶんは「調達待ち」として残す
--       → 入荷したら［不足分を手配］で不足分だけ確保
--
--   ここで完成するのは「受注から手配・在庫確保まで」です。
--   発送・納品・返却はまだ作っていません。
--
--   守っていること
--     ・在庫を動かす入口は inv_contract_fulfill_start だけ
--     ・inventory_items.status は直接UPDATEしない。
--       既存の inv_sale_reserve / inv_rental_request_create + inv_rental_allocate を通し、
--       最終的に共通ロック inv_reserve_available_item() を必ず通る
--     ・在庫が足りなくても、仮の個体（架空のS/N・管理番号）は作らない
--     ・商品コードが無い明細を、似た型番で勝手に置き換えない
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 51-0) 48で表の名前を変えたときに残った、古い主キー名の後始末
--       （新しく作ったDBと、順に流してきたDBの形をそろえるため）
-- ------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_constraint
              where conname = 'inventory_quote_access_pkey'
                and conrelid = to_regclass('public.inventory_public_access')) then
    alter table public.inventory_public_access
      rename constraint inventory_quote_access_pkey to inventory_public_access_pkey;
  end if;
end $$;

-- ------------------------------------------------------------
-- 51-1) 契約明細とレンタル申込のつなぎ
--
--     ［不足分を手配］を押すたびに新しい申込を作らないよう、
--     契約明細に「この明細のレンタル申込」を覚えておく。
-- ------------------------------------------------------------
alter table public.inventory_contract_items
  add column if not exists rental_request_id bigint
    references public.inventory_rental_requests(id) on delete set null;

comment on column public.inventory_contract_items.rental_request_id is
  'この明細のレンタル申込。再手配のときは新しく作らずこれを使い回す。';

-- ------------------------------------------------------------
-- 51-2) 契約が確保した実物の記録
--
--     「どの契約の、どの明細が、どの実物を確保したか」を必ず追えるようにする。
--     取り消すときも、ここに記録されたものだけを戻す。
-- ------------------------------------------------------------
create table if not exists public.inventory_contract_fulfillments (
  id          bigint generated by default as identity primary key,
  contract_id bigint not null references public.inventory_contracts(id) on delete cascade,
  contract_item_id bigint not null references public.inventory_contract_items(id) on delete cascade,
  kind        text not null,
  item_id     text references public.inventory_items(id) on delete set null,
  rental_request_id bigint references public.inventory_rental_requests(id) on delete set null,
  qty         integer not null default 1,
  status      text not null default '確保済み',
  source      text not null default 'COMMERCE',
  reference   text,                     -- 契約番号など、あとで探すための手がかり
  actor       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint inventory_contract_fulfillments_kind_chk check (kind in ('sale', 'rental')),
  constraint inventory_contract_fulfillments_status_chk check
    (status in ('確保済み', '解除', '発送済み', '貸出中', '返却済み'))
);

comment on table public.inventory_contract_fulfillments is
  '契約が確保した実物の記録。どの契約のどの明細が、どの個体・どのレンタル申込を押さえたか。
   契約を取り消すときも、ここに載っているものだけを戻す（商品コード単位では戻さない）。';

create index if not exists inventory_contract_fulfillments_contract_idx
  on public.inventory_contract_fulfillments (contract_id, contract_item_id, id);
create index if not exists inventory_contract_fulfillments_item_idx
  on public.inventory_contract_fulfillments (item_id);

-- 同じ明細に同じ個体を二重に紐付けない
create unique index if not exists inventory_contract_fulfillments_item_uk
  on public.inventory_contract_fulfillments (contract_item_id, item_id)
  where item_id is not null and status <> '解除';
-- 1台の個体を、同時に2つの契約が押さえない
create unique index if not exists inventory_contract_fulfillments_item_once_uk
  on public.inventory_contract_fulfillments (item_id)
  where item_id is not null and status <> '解除';

-- ------------------------------------------------------------
-- 51-3) 明細と契約ヘッダの手配状態をまとめ直す
--
--     ヘッダは明細の集約。
--     「調達待ち」が1件でもあれば、ヘッダを準備完了にしない。
-- ------------------------------------------------------------
create or replace function public.inv_contract_fulfillment_recalc(p_contract_id bigint)
returns text
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  c        public.inventory_contracts;
  it       public.inventory_contract_items;
  v_have   integer;
  v_stock  integer := 0;   -- 在庫を伴う明細の数
  v_done   integer := 0;   -- 必要数がそろった明細
  v_short  integer := 0;   -- 調達待ちの明細
  v_touch  integer := 0;   -- 少しでも確保した明細
  v_new    text;
begin
  select * into c from public.inventory_contracts where id = p_contract_id;
  if not found then raise exception '契約が見つかりません（%）', p_contract_id; end if;

  for it in select * from public.inventory_contract_items
             where contract_id = p_contract_id order by sort_no, id
  loop
    if it.kind not in ('sale', 'rental') then
      -- 在庫を伴わない明細（キッティング・研修・月額サービスなど）
      if it.fulfillment_status <> '手配不要' then
        update public.inventory_contract_items
           set fulfillment_status = '手配不要', updated_at = now() where id = it.id;
      end if;
      continue;
    end if;

    v_stock := v_stock + 1;
    select count(*) into v_have
      from public.inventory_contract_fulfillments
     where contract_item_id = it.id and status <> '解除';

    if v_have >= it.qty then
      v_done := v_done + 1;
      v_new := '確保済み';
    elsif v_have > 0 or it.fulfillment_status in ('手配中', '調達待ち') then
      v_short := v_short + 1;
      v_new := '調達待ち';
    else
      v_new := '未手配';
    end if;
    if v_have > 0 then v_touch := v_touch + 1; end if;

    if v_new <> it.fulfillment_status or v_have <> it.allocated_qty then
      update public.inventory_contract_items
         set fulfillment_status = v_new,
             allocated_qty = v_have,
             procure_qty = greatest(it.qty - v_have, 0),
             updated_at = now()
       where id = it.id;
    end if;
  end loop;

  -- ヘッダは明細の集約
  if v_stock = 0 then
    -- 在庫を伴う明細が無い契約（作業と月額サービスだけ）
    v_new := case when c.fulfillment_status = '未手配' then '未手配' else '準備完了' end;
  elsif v_done = v_stock then
    v_new := '準備完了';
  elsif v_short > 0 or v_touch > 0 then
    v_new := '手配中';
  else
    -- 1台も押さえていない（まだ手配していない／全部戻した）
    v_new := '未手配';
  end if;

  -- 発送以降まで進んでいる契約は、ここでは戻さない
  if c.fulfillment_status in ('発送済み', '貸出中', '完了', '返却待ち', '返却済み') then
    return c.fulfillment_status;
  end if;

  if v_new <> c.fulfillment_status then
    update public.inventory_contracts
       set fulfillment_status = v_new, updated_at = now() where id = p_contract_id;
  end if;
  return v_new;
end $$;

comment on function public.inv_contract_fulfillment_recalc is
  '契約明細と契約ヘッダの手配状態をまとめ直す。ヘッダは明細の集約で、
   「調達待ち」が1件でも残っていれば準備完了にしない。';

-- ------------------------------------------------------------
-- 51-4) 手配に進む（在庫を実際に押さえる唯一の入口）
--
--     p_only_short = true にすると、足りない明細だけを対象にする
--     （［不足分を手配］。すでに確保できている個体には触らない）。
--
--     二重実行を止めるため、いちばん最初に契約行を for update で押さえる。
--     画面のボタンを disabled にするだけには頼らない。
--     手配してよいかも、ここでもう一度確かめる（画面を開いてから
--     状態が変わっているかもしれないため）。
-- ------------------------------------------------------------
create or replace function public.inv_contract_fulfill_start(
  p_contract_id bigint,
  p_only_short  boolean default false
) returns jsonb
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  c        public.inventory_contracts;
  it       public.inventory_contract_items;
  v_can    jsonb;
  v_need   integer;
  v_have   integer;
  v_item   public.inventory_items;
  v_req    jsonb;
  v_rr     public.inventory_rental_requests;
  v_ids    text[];
  v_id     text;
  v_no     text;
  v_got    integer;
  v_total  integer := 0;   -- このボタンで新しく確保できた数
  v_short  integer := 0;   -- 足りないままの数
  v_stop   text[]  := '{}';-- 自動手配できなかった明細のお知らせ
  i        integer;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;

  -- ここで直列化する。同時に2回押されても、片方は待たされてから走る
  select * into c from public.inventory_contracts where id = p_contract_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_contract_id; end if;
  v_no := public.inv_contract_no(c.deal_id, c.seq);

  -- 押すまでに状態が変わっているかもしれないので、ここでも確かめる
  v_can := public.inv_contract_can_fulfill(p_contract_id);
  if not (v_can->>'ok')::boolean then
    return jsonb_build_object('ok', false, 'reason', v_can->>'reason',
                              'allocated', 0, 'short', 0);
  end if;
  if c.fulfillment_status in ('発送済み', '貸出中', '完了', '返却待ち', '返却済み') then
    return jsonb_build_object('ok', false,
      'reason', 'この契約はすでに「' || c.fulfillment_status || '」です', 'allocated', 0, 'short', 0);
  end if;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text, v_no,
          case when p_only_short then '不足分の再手配' else '手配開始' end,
          c.fulfillment_status, '在庫の確保をはじめます');

  for it in select * from public.inventory_contract_items
             where contract_id = p_contract_id and kind in ('sale', 'rental')
             order by sort_no, id
             for update
  loop
    select count(*) into v_have
      from public.inventory_contract_fulfillments
     where contract_item_id = it.id and status <> '解除';
    v_need := greatest(it.qty - v_have, 0);

    if v_need = 0 then continue; end if;
    if p_only_short and it.fulfillment_status not in ('調達待ち', '手配中') then continue; end if;

    -- 契約はスナップショットなので、商品コードが残っていないことがある。
    -- 似た型番や後継機で勝手に代用しない。担当者に確認してもらう。
    if nullif(btrim(coalesce(it.product_code, '')), '') is null then
      v_stop := v_stop || (it.name || '：自動手配できません（商品コードを確認してください）');
      continue;
    end if;
    if not exists (select 1 from public.inventory_products where code = it.product_code) then
      v_stop := v_stop || (it.name || '：商品コード ' || it.product_code || ' が見つかりません');
      continue;
    end if;

    -- ここから実際に取りにいく。1台も取れなくても「試した」ことが分かるよう、
    -- 先に手配中にしておく（そうしないと未手配のままになり、調達待ちに見えない）
    update public.inventory_contract_items
       set fulfillment_status = '手配中', updated_at = now()
     where id = it.id and fulfillment_status in ('未手配', '手配中', '調達待ち');
    v_got := 0;

    if it.kind = 'sale' then
      -- ── 販売：必要数だけ販売予約する ──
      for i in 1 .. v_need loop
        begin
          v_item := public.inv_sale_reserve(it.product_code, 'COMMERCE', v_no,
                                            '契約 ' || v_no || ' / ' || it.name);
        exception when others then
          if sqlerrm like '%在庫がありません%' then
            exit;                      -- 在庫切れ。ここまでで止めて、残りは調達待ちにする
          else
            raise;
          end if;
        end;
        insert into public.inventory_contract_fulfillments
          (contract_id, contract_item_id, kind, item_id, qty, status, source, reference, actor)
        values (p_contract_id, it.id, 'sale', v_item.id, 1, '確保済み', 'COMMERCE', v_no, public.inv_actor());
        v_got := v_got + 1;
      end loop;

    else
      -- ── レンタル：申込を作って（あれば使い回して）個体を割り当てる ──
      if not exists (select 1 from public.inventory_products
                      where code = it.product_code and kind = 'individual'
                        and coalesce(rental_enabled, false)) then
        v_stop := v_stop || (it.name || '：この商品は8RENTの掲載が入っていないので自動手配できません');
        continue;
      end if;

      -- 前の申込が取り消されていたら、それは使い回せない（新しく作る）
      if it.rental_request_id is not null
         and not exists (select 1 from public.inventory_rental_requests
                          where id = it.rental_request_id
                            and status in ('希望受付', '在庫・調達確認', '個体割当')) then
        update public.inventory_contract_items
           set rental_request_id = null, updated_at = now() where id = it.id
        returning * into it;
      end if;

      if it.rental_request_id is null then
        v_req := public.inv_rental_request_create(
          array[it.product_code], coalesce(c.customer_name, c.company, 'ご契約者'),
          it.qty, c.company, c.email, c.phone, c.start_date, it.months, false,
          '契約 ' || v_no || ' からの手配', jsonb_build_object('contract_no', v_no));
        update public.inventory_contract_items
           set rental_request_id = (v_req->>'request_id')::bigint, updated_at = now()
         where id = it.id
        returning * into it;
        insert into public.inventory_transactions
          (actor, ref_kind, ref_id, label, action, before_value, after_value)
        values (public.inv_actor(), 'contract', c.id::text, v_no, 'レンタル申込作成', null,
                it.name || '：申込 #' || it.rental_request_id || '（' || it.qty || '台）');
      end if;

      v_rr := public.inv_rental_allocate(it.rental_request_id);
      v_ids := coalesce(v_rr.item_ids, '{}'::text[]);
      foreach v_id in array v_ids loop
        if not exists (select 1 from public.inventory_contract_fulfillments
                        where contract_item_id = it.id and item_id = v_id and status <> '解除') then
          insert into public.inventory_contract_fulfillments
            (contract_id, contract_item_id, kind, item_id, rental_request_id,
             qty, status, source, reference, actor)
          values (p_contract_id, it.id, 'rental', v_id, it.rental_request_id,
                  1, '確保済み', 'COMMERCE', v_no, public.inv_actor());
          v_got := v_got + 1;
        end if;
      end loop;
      insert into public.inventory_transactions
        (actor, ref_kind, ref_id, label, action, before_value, after_value)
      values (public.inv_actor(), 'contract', c.id::text, v_no, 'レンタル割当', null,
              it.name || '：申込 #' || it.rental_request_id || ' に ' || v_got || '台割当');
    end if;

    v_total := v_total + v_got;
    if v_got < v_need then
      v_short := v_short + (v_need - v_got);
      insert into public.inventory_transactions
        (actor, ref_kind, ref_id, label, action, before_value, after_value)
      values (public.inv_actor(), 'contract', c.id::text, v_no, '調達待ち', null,
              it.name || '：必要 ' || it.qty || '台／確保 ' || (v_have + v_got)
                || '台／調達 ' || (v_need - v_got) || '台');
    elsif v_got > 0 then
      insert into public.inventory_transactions
        (actor, ref_kind, ref_id, label, action, before_value, after_value)
      values (public.inv_actor(), 'contract', c.id::text, v_no, '一部確保', null,
              it.name || '：' || v_got || '台を確保（必要 ' || it.qty || '台）');
    end if;
  end loop;

  perform public.inv_contract_fulfillment_recalc(p_contract_id);
  select * into c from public.inventory_contracts where id = p_contract_id;

  -- 実際に1台でも押さえたときだけ、契約を「履行中」へ進める。
  -- ボタンを押しただけで実態より先に進めない。
  if c.status = '確定' and exists (select 1 from public.inventory_contract_fulfillments
                                    where contract_id = p_contract_id and status <> '解除') then
    update public.inventory_contracts
       set status = '履行中', actor = public.inv_actor(), updated_at = now()
     where id = p_contract_id;
    update public.inventory_deals
       set status = '手配', actor = public.inv_actor()
     where id = c.deal_id and status in ('契約', '支払条件確定');
  end if;

  if c.fulfillment_status = '準備完了' then
    insert into public.inventory_transactions
      (actor, ref_kind, ref_id, label, action, before_value, after_value)
    values (public.inv_actor(), 'contract', c.id::text, v_no, '手配完了', null,
            '必要数がすべてそろいました');
  end if;

  return jsonb_build_object(
    'ok', true, 'allocated', v_total, 'short', v_short,
    'fulfillment_status', c.fulfillment_status,
    'stopped', to_jsonb(v_stop),
    'reason', case
      when array_length(v_stop, 1) > 0 then '自動手配できない明細があります'
      when v_short > 0 then '在庫が足りないぶんは調達待ちにしました'
      when v_total > 0 then '必要数を確保しました'
      else '新しく確保するものはありませんでした' end);
end $$;

comment on function public.inv_contract_fulfill_start is
  '契約の手配を始める（在庫を実際に押さえる唯一の入口）。
   販売は inv_sale_reserve、レンタルは inv_rental_request_create + inv_rental_allocate を通すので、
   最終的に共通ロック inv_reserve_available_item を必ず通る。
   足りないぶんは調達待ちとして残し、仮の個体は作らない。
   商品コードが無い・掲載が無い明細は、代わりの商品を推測せず担当者に止める。
   p_only_short = true で「不足分だけ」。契約行を for update で押さえるので二重実行に強い。';

-- ------------------------------------------------------------
-- 51-5) この契約が確保したものだけを戻す（発送前のみ）
--
--     商品コード単位では戻さない。同じ商品を別の案件が押さえていることがあるため。
--     発送済み・貸出中になった個体は、契約の取消だけを理由に自動で戻さない
--     （返品・返却の実物確認が要る）。
-- ------------------------------------------------------------
create or replace function public.inv_contract_fulfill_release(
  p_contract_id bigint,
  p_reason      text default null
) returns jsonb
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  c      public.inventory_contracts;
  f      public.inventory_contract_fulfillments;
  it     public.inventory_items;
  v_no   text;
  v_back integer := 0;
  v_keep integer := 0;
  v_reqs bigint[] := '{}';
  v_req  bigint;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_contract_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_contract_id; end if;
  v_no := public.inv_contract_no(c.deal_id, c.seq);

  for f in select * from public.inventory_contract_fulfillments
            where contract_id = p_contract_id and status = '確保済み'
            order by id
            for update
  loop
    select * into it from public.inventory_items where id = f.item_id;
    if it.id is null then
      update public.inventory_contract_fulfillments
         set status = '解除', updated_at = now() where id = f.id;
      continue;
    end if;
    -- 発送してしまったものは自動で戻さない
    if it.status in ('貸出中', '売却済') then
      v_keep := v_keep + 1;
      continue;
    end if;

    if f.kind = 'sale' then
      if it.status = '販売予約' then
        perform public.inv_item_op(f.item_id, '予約解除', null,
                                   '契約 ' || v_no || ' の取消');
      end if;
      update public.inventory_contract_fulfillments
         set status = '解除', updated_at = now() where id = f.id;
      v_back := v_back + 1;
    else
      -- レンタルは申込ごと取り消す（同じ申込の個体をまとめて戻す）
      if f.rental_request_id is not null and not (f.rental_request_id = any(v_reqs)) then
        v_reqs := v_reqs || f.rental_request_id;
      end if;
      update public.inventory_contract_fulfillments
         set status = '解除', updated_at = now() where id = f.id;
      v_back := v_back + 1;
    end if;
  end loop;

  foreach v_req in array v_reqs loop
    perform public.inv_rental_set_status(v_req, 'キャンセル');
    -- 取り消した申込は使い回せないので、明細とのつながりも切っておく
    update public.inventory_contract_items
       set rental_request_id = null, updated_at = now()
     where contract_id = p_contract_id and rental_request_id = v_req;
  end loop;

  if v_back > 0 then
    insert into public.inventory_transactions
      (actor, ref_kind, ref_id, label, action, before_value, after_value)
    values (public.inv_actor(), 'contract', c.id::text, v_no, '予約解除', null,
            v_back || '台を在庫へ戻しました'
              || coalesce('（' || nullif(btrim(coalesce(p_reason, '')), '') || '）', ''));
  end if;

  -- 1台も残っていない明細は「未手配」に戻す。
  -- 調達待ちのままだと「仕入れ待ち」に見えてしまうが、実際は意図して手放した状態なので。
  update public.inventory_contract_items ci
     set fulfillment_status = '未手配', updated_at = now()
   where ci.contract_id = p_contract_id
     and ci.kind in ('sale', 'rental')
     and ci.fulfillment_status in ('手配中', '調達待ち', '確保済み')
     and not exists (select 1 from public.inventory_contract_fulfillments cf
                      where cf.contract_item_id = ci.id and cf.status <> '解除');

  perform public.inv_contract_fulfillment_recalc(p_contract_id);

  -- 全部戻して何も押さえていないなら、契約は「確定」に戻す
  -- （履行中は、実際に何かを押さえているあいだの状態にしておく）
  if c.status = '履行中'
     and not exists (select 1 from public.inventory_contract_fulfillments
                      where contract_id = p_contract_id and status <> '解除') then
    update public.inventory_contracts
       set status = '確定', actor = public.inv_actor(), updated_at = now()
     where id = p_contract_id;
  end if;

  return jsonb_build_object('released', v_back, 'kept', v_keep,
    'reason', case when v_keep > 0
                   then v_keep || '台は発送済み・売却済みなので戻していません（返品・返却の手続きが要ります）'
                   else null end);
end $$;

comment on function public.inv_contract_fulfill_release is
  'この契約が確保した個体だけを在庫へ戻す。商品コード単位では戻さない
   （同じ商品を別の案件が押さえていることがあるため）。
   発送済み・貸出中・売却済みの個体は自動で戻さない。';

-- ------------------------------------------------------------
-- 51-6) 契約の取消に、確保したものを戻す処理をつなぐ
-- ------------------------------------------------------------
create or replace function public.inv_contract_cancel(p_id bigint, p_reason text default null)
returns public.inventory_contracts
language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  c public.inventory_contracts;
  v_rel jsonb;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  select * into c from public.inventory_contracts where id = p_id for update;
  if not found then raise exception '契約が見つかりません（%）', p_id; end if;
  if c.status = '取消' then raise exception 'この契約はすでに取消です'; end if;

  -- 発送してしまった個体があるときは、実物の確認が要るので自動では取り消さない
  if exists (select 1 from public.inventory_contract_fulfillments f
               join public.inventory_items i on i.id = f.item_id
              where f.contract_id = p_id and f.status = '確保済み'
                and i.status in ('貸出中', '売却済')) then
    raise exception 'すでに発送・売却した個体があります。返品・返却の手続きをしてから取り消してください';
  end if;

  -- この契約が押さえたものだけを在庫へ戻す
  v_rel := public.inv_contract_fulfill_release(p_id, p_reason);

  update public.inventory_contracts
     set status = '取消',
         internal_note = coalesce(internal_note || E'\n', '')
           || coalesce('取消：' || nullif(btrim(coalesce(p_reason, '')), ''), '取消'),
         actor = public.inv_actor(), updated_at = now()
   where id = p_id
  returning * into c;

  insert into public.inventory_transactions
    (actor, ref_kind, ref_id, label, action, before_value, after_value)
  values (public.inv_actor(), 'contract', c.id::text,
          public.inv_contract_no(c.deal_id, c.seq), '契約取消', null,
          coalesce(nullif(btrim(coalesce(p_reason, '')), ''), '取消')
            || '／在庫へ戻した数 ' || coalesce(v_rel->>'released', '0'));

  perform public.inv_contract_payment_recalc(p_id);
  return c;
end $$;

comment on function public.inv_contract_cancel is
  '契約を取り消す。この契約が押さえた個体だけを在庫へ戻す（他の案件の予約には触らない）。
   すでに発送・売却した個体があるときは、実物の確認が要るので取り消せない。';

-- ------------------------------------------------------------
-- 51-7) 画面が読む手配の一覧
-- ------------------------------------------------------------
create or replace view public.inv_contract_fulfillment_list as
select it.id            as contract_item_id,
       it.contract_id,
       it.sort_no, it.kind, it.name, it.spec, it.product_code, it.qty,
       it.fulfillment_status,
       it.rental_request_id,
       coalesce(f.got, 0) as allocated_qty,
       -- 在庫を伴わない明細（キッティング・研修など）は調達待ちにしない
       case when it.kind in ('sale', 'rental')
            then greatest(it.qty - coalesce(f.got, 0), 0) else 0 end as procure_qty
  from public.inventory_contract_items it
  left join (select contract_item_id, count(*) as got
               from public.inventory_contract_fulfillments
              where status <> '解除' group by contract_item_id) f
    on f.contract_item_id = it.id;

comment on view public.inv_contract_fulfillment_list is
  '契約明細ごとの手配の様子（必要数・確保できた数・調達待ちの数）。';

-- ------------------------------------------------------------
-- 51-8) 権限
-- ------------------------------------------------------------
alter table public.inventory_contract_fulfillments enable row level security;
drop policy if exists "inventory_contract_fulfillments read" on public.inventory_contract_fulfillments;
create policy "inventory_contract_fulfillments read" on public.inventory_contract_fulfillments
  for select to authenticated using (true);

revoke all on public.inventory_contract_fulfillments from anon, authenticated;
grant select on public.inventory_contract_fulfillments to authenticated;
grant select on public.inv_contract_fulfillment_list   to authenticated;

revoke all on function public.inv_contract_fulfillment_recalc(bigint)      from public, anon, authenticated;
revoke all on function public.inv_contract_fulfill_start(bigint,boolean)   from public, anon;
revoke all on function public.inv_contract_fulfill_release(bigint,text)    from public, anon;
grant execute on function public.inv_contract_fulfill_start(bigint,boolean) to authenticated;
grant execute on function public.inv_contract_fulfill_release(bigint,text)  to authenticated;

commit;

notify pgrst, 'reload schema';
