-- ============================================================
-- 個体別チャネル情報(inventory_channels)と商品別チャネル情報
-- (新設 inventory_channel_listings)を分離するmigration
--
--   背景：P-00410 / rakuten を調べたところ、
--     rows = 20 / sku_count = 1 / item_id_count = 20
--   つまり「1つの楽天商品(SKU) に対して実在庫20台が紐づく」という
--   正しいデータであり、重複ではなかった。前回追加した
--   UNIQUE(product_code, channel)（item_idを考慮しない一意制約）は
--   このデータ構造と矛盾する設計ミスであり、これを取り除く。
--
--   このファイルは setup.sql 全体ではなく、今回分の変更だけを
--   本番Supabaseの SQL Editor に貼り付けて実行するためのものです。
--   実行後は、以後の運用のため zaiko/setup.sql も最新版を通しで
--   実行しておいてください（このmigrationの内容を含んでいるので
--   二重に実行しても安全です）。
--
--   このmigrationが変更するもの：
--     1. 個体×チャネルの重複が無いことを確認してから進める（あれば中断）
--     2. 誤って作られた可能性のある商品まるごとの一意制約を削除
--        （個体を考慮しないUNIQUE(product_code, channel)）
--     3. inventory_channel_listings（商品×チャネル）を新設
--     4. inventory_channels の「商品まるごと」行（item_id is null）を
--        inventory_channel_listings へ移す。個体の行（item_id is not null。
--        例: P-00410 配下の CF-00001〜CF-00020）は一切変更しない
--     5. inv_listing_set / inv_listings_import / inv_rakuten_apply_one /
--        inv_rakuten_sync_apply を新しいテーブル構成に合わせて更新
--
--   何度実行しても安全です（移行済みなら何もしません）。
-- ============================================================

-- ------------------------------------------------------------
-- 1) 個体×チャネルに重複が無いことを確認する（あれば中断してdeleteに進まない）
-- ------------------------------------------------------------
do $$
declare
  v_item_id text;
  v_channel text;
  v_count   integer;
begin
  select item_id, channel, count(*) into v_item_id, v_channel, v_count
    from public.inventory_channels
   where item_id is not null
   group by item_id, channel
  having count(*) > 1
   limit 1;

  if v_item_id is not null then
    raise exception '個体×チャネルに重複があります（item_id=%, channel=%, %件）。'
      '先にこの重複を解消してから、このmigrationを再実行してください。',
      v_item_id, v_channel, v_count;
  end if;
end $$;

-- ------------------------------------------------------------
-- 2) 誤って作られた可能性のある「商品まるごと」の一意制約を削除
--    （item_idを考慮しないUNIQUE(product_code, channel)。
--     本来のデータでは1商品に対して複数個体×同一チャネルの行が
--     あり得るため、この制約自体が誤り）
-- ------------------------------------------------------------
drop index if exists public.inventory_channels_pc_idx;

-- 個体×チャネルの一意制約が正しく入っていることを保証する
-- （既存で入っていれば何もしない）
create unique index if not exists inventory_channels_item_idx
  on public.inventory_channels (item_id, channel) where item_id is not null;

-- ------------------------------------------------------------
-- 3) 商品×チャネル（掲載情報）専用のテーブルを新設
-- ------------------------------------------------------------
create table if not exists public.inventory_channel_listings (
  id              bigint generated by default as identity primary key,
  product_code    text not null references public.inventory_products(code) on delete cascade,
  channel         text not null,
  state           text,        -- 出品中 / 出品停止 / 保留 / 売り切れ / 出品中止 / 販売済み
  sku             text,        -- そのモールでの商品コード（楽天itemCode等）
  price           numeric,
  url             text,
  note            text,
  api_synced_at   timestamptz, -- APIで最後に取得・反映した時刻（手入力のみなら null）
  api_sync_status text,        -- 直近の同期結果（'ok' / エラーメッセージ 等）
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

comment on table public.inventory_channel_listings is
  '商品×販売チャネルの「掲載」情報（1つのSKU・URL・価格を、複数の実在庫個体が共有する）。
   個体ごとの出品状態は引き続き inventory_channels（item_id必須）で管理する。';

create unique index if not exists inventory_channel_listings_idx
  on public.inventory_channel_listings (product_code, channel);
create index if not exists inventory_channel_listings_sku_idx
  on public.inventory_channel_listings (channel, sku);

drop trigger if exists inventory_channel_listings_touch on public.inventory_channel_listings;
create trigger inventory_channel_listings_touch before update on public.inventory_channel_listings
  for each row execute function public.inv_touch();

-- ------------------------------------------------------------
-- 4) 既存の「商品まるごと」行（item_id is null）を移す。
--    個体の行（item_id is not null）は一切触れない。
--    移行件数を確認できてから delete する（一致しなければ中断・ロールバック）
-- ------------------------------------------------------------
do $$
declare
  v_before_count integer;
  v_after_count  integer;
begin
  select count(*) into v_before_count from public.inventory_channels where item_id is null;

  insert into public.inventory_channel_listings
    (product_code, channel, state, sku, price, url, note, updated_at)
  select product_code, channel, state, sku, price, url, note, updated_at
    from public.inventory_channels
   where item_id is null
  on conflict (product_code, channel) do nothing;

  select count(*) into v_after_count from public.inventory_channel_listings;

  if v_after_count < v_before_count then
    raise exception '移行件数が想定より少ないため中断しました'
      '（商品まるごとの行 %件 に対し、移行先の件数は %件）。'
      'inventory_channels の delete は行っていません。内容をご確認ください。',
      v_before_count, v_after_count;
  end if;

  delete from public.inventory_channels where item_id is null;

  raise notice '商品まるごとの出品情報 % 件を inventory_channel_listings へ移しました', v_before_count;
end $$;

-- inventory_channels は個体専用になったので、商品まるごと用の一意制約は不要
drop index if exists public.inventory_channels_prod_idx;

-- ------------------------------------------------------------
-- 5) inv_listing_set を、個体(inventory_channels)／商品(inventory_channel_listings)
--    の振り分けに対応させる。戻り値の型が変わるため drop してから作り直す
-- ------------------------------------------------------------
drop function if exists public.inv_listing_set(text,text,text,text,text,numeric,text,text);

create function public.inv_listing_set(
  p_item_id text,
  p_code    text,
  p_channel text,
  p_state   text,
  p_sku     text default null,
  p_price   numeric default null,
  p_url     text default null,
  p_note    text default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_code   text := p_code;
  v_before text;
  v_row    jsonb;
  v_empty  boolean;
  v_st     text := nullif(trim(coalesce(p_state, '')), '');
  v_sku    text := nullif(trim(coalesce(p_sku, '')), '');
  v_url    text := nullif(trim(coalesce(p_url, '')), '');
  v_note   text := nullif(trim(coalesce(p_note, '')), '');
begin
  if not public.inv_can_edit() then
    raise exception '出品情報を変えられる権限がありません';
  end if;
  if v_st = '未出品' then v_st := null; end if;
  v_empty := v_st is null and v_sku is null and v_url is null and v_note is null and p_price is null;

  if p_item_id is not null then
    -- 個体1台ぶん（既存どおり inventory_channels）
    select product_code into v_code from public.inventory_items where id = p_item_id;
    if not found then
      raise exception '個体 % が見つかりません', p_item_id;
    end if;
    select state into v_before from public.inventory_channels
     where item_id = p_item_id and channel = p_channel;

    if v_empty then
      delete from public.inventory_channels where item_id = p_item_id and channel = p_channel;
    else
      insert into public.inventory_channels
        (product_code, item_id, channel, state, sku, price, url, note, updated_at)
      values (v_code, p_item_id, p_channel, v_st, v_sku, p_price, v_url, v_note, now())
      on conflict (item_id, channel) where item_id is not null
      do update set state = excluded.state, sku = excluded.sku, price = excluded.price,
                    url = excluded.url, note = excluded.note, updated_at = now()
      returning to_jsonb(inventory_channels.*) into v_row;
    end if;
  else
    -- 商品まるごと（inventory_channel_listings）
    if v_code is null then
      raise exception '商品が指定されていません';
    end if;
    select state into v_before from public.inventory_channel_listings
     where product_code = v_code and channel = p_channel;

    if v_empty then
      delete from public.inventory_channel_listings where product_code = v_code and channel = p_channel;
    else
      insert into public.inventory_channel_listings
        (product_code, channel, state, sku, price, url, note, updated_at)
      values (v_code, p_channel, v_st, v_sku, p_price, v_url, v_note, now())
      on conflict (product_code, channel)
      do update set state = excluded.state, sku = excluded.sku, price = excluded.price,
                    url = excluded.url, note = excluded.note, updated_at = now()
      returning to_jsonb(inventory_channel_listings.*) into v_row;
    end if;
  end if;

  if coalesce(v_before, '未出品') is distinct from coalesce(v_st, '未出品') then
    insert into public.inventory_transactions
      (actor, ref_kind, ref_id, label, action, before_value, after_value)
    values
      (public.inv_actor(),
       case when p_item_id is not null then 'item' else 'product' end,
       coalesce(p_item_id, v_code), p_channel, '出品',
       coalesce(v_before, '未出品'), coalesce(v_st, '未出品'));
  end if;

  return v_row;
end $$;

comment on function public.inv_listing_set is
  '販売サイトごとの出品情報を入れ直す。個体1台なら inventory_channels、
   商品まるごとなら inventory_channel_listings に書く。空にすると未出品。';

grant execute on function public.inv_listing_set(text,text,text,text,text,numeric,text,text) to authenticated;

-- ------------------------------------------------------------
-- 6) inv_listings_import も同様に振り分ける
-- ------------------------------------------------------------
create or replace function public.inv_listings_import(p_rows jsonb)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  r       jsonb;
  v_item  text;
  v_code  text;
  v_added integer := 0;
  v_kept  integer := 0;
begin
  if not public.inv_is_admin() then
    raise exception '取り込みは管理者だけができます';
  end if;

  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb)) loop
    v_item := nullif(r->>'item_id', '');
    if v_item is not null then
      select product_code into v_code from public.inventory_items where id = v_item;
      if not found then continue; end if;
    else
      v_code := nullif(r->>'product_code', '');
      if v_code is null
         or not exists (select 1 from public.inventory_products where code = v_code) then
        continue;
      end if;
    end if;

    if v_item is not null then
      if exists (select 1 from public.inventory_channels where item_id = v_item and channel = r->>'channel') then
        update public.inventory_channels set
          state = coalesce(state, nullif(r->>'state', '')),
          sku   = coalesce(sku,   nullif(r->>'sku', '')),
          price = coalesce(price, (nullif(r->>'price', ''))::numeric),
          url   = coalesce(url,   nullif(r->>'url', '')),
          note  = coalesce(note,  nullif(r->>'note', ''))
         where item_id = v_item and channel = r->>'channel';
        v_kept := v_kept + 1;
      else
        insert into public.inventory_channels
          (product_code, item_id, channel, state, sku, price, url, note)
        values
          (v_code, v_item, r->>'channel', nullif(r->>'state', ''),
           nullif(r->>'sku', ''), (nullif(r->>'price', ''))::numeric,
           nullif(r->>'url', ''), nullif(r->>'note', ''));
        v_added := v_added + 1;
      end if;
    else
      if exists (select 1 from public.inventory_channel_listings where product_code = v_code and channel = r->>'channel') then
        update public.inventory_channel_listings set
          state = coalesce(state, nullif(r->>'state', '')),
          sku   = coalesce(sku,   nullif(r->>'sku', '')),
          price = coalesce(price, (nullif(r->>'price', ''))::numeric),
          url   = coalesce(url,   nullif(r->>'url', '')),
          note  = coalesce(note,  nullif(r->>'note', ''))
         where product_code = v_code and channel = r->>'channel';
        v_kept := v_kept + 1;
      else
        insert into public.inventory_channel_listings
          (product_code, channel, state, sku, price, url, note)
        values
          (v_code, r->>'channel', nullif(r->>'state', ''),
           nullif(r->>'sku', ''), (nullif(r->>'price', ''))::numeric,
           nullif(r->>'url', ''), nullif(r->>'note', ''));
        v_added := v_added + 1;
      end if;
    end if;
  end loop;

  return jsonb_build_object('added', v_added, 'kept', v_kept);
end $$;

comment on function public.inv_listings_import is
  '既存在庫CSVの出品状態を移す。個体1台なら inventory_channels、商品まるごとなら
   inventory_channel_listings に入れる。すでにある出品情報は上書きしない。';

grant execute on function public.inv_listings_import(jsonb) to authenticated;

-- ------------------------------------------------------------
-- 7) 楽天連携（inv_rakuten_apply_one / inv_rakuten_sync_apply）を
--    inventory_channel_listings に書くよう更新する。
--    CREATE OR REPLACE なので、まだ存在しなくても（先に zaiko/setup.sql の
--    楽天連携セクションを実行していなくても）そのまま作られるだけで安全です。
-- ------------------------------------------------------------
create or replace function public.inv_rakuten_apply_one(
  p_code text,
  p_item jsonb
) returns jsonb
language plpgsql security invoker set search_path = public as $$
declare
  ex           jsonb := coalesce(p_item->'extracted', '{}'::jsonb);
  v_item_code  text  := nullif(btrim(coalesce(p_item->>'item_code','')), '');
  v_url        text  := nullif(btrim(coalesce(p_item->>'item_url','')), '');
  v_price      numeric;
  before_row   public.inventory_products;
  after_row    public.inventory_products;
  before_snap  jsonb;
  after_snap   jsonb;
  v_chan_new   boolean := false;
  v_changed    boolean;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;

  select * into before_row from public.inventory_products where code = p_code for update;
  if not found then
    raise exception '商品が見つかりません（%）', p_code;
  end if;
  before_snap := to_jsonb(before_row) - 'updated_at' - 'rakuten_synced_at';

  v_price := nullif(p_item->>'price', '')::numeric;

  update public.inventory_products set
    maker             = coalesce(nullif(maker,''), nullif(p_item->>'maker','')),
    model             = coalesce(nullif(model,''), nullif(p_item->>'model','')),
    description       = coalesce(nullif(description,''), nullif(p_item->>'caption','')),
    image_url         = coalesce(nullif(image_url,''), nullif(p_item->>'image_url','')),
    images            = case when jsonb_array_length(coalesce(images,'[]'::jsonb)) = 0
                              and jsonb_typeof(p_item->'images') = 'array'
                         then p_item->'images' else images end,
    cpu               = coalesce(nullif(cpu,''), nullif(ex->>'cpu','')),
    cpu_gen           = coalesce(nullif(cpu_gen,''), nullif(ex->>'cpu_gen','')),
    memory_size       = coalesce(nullif(memory_size,''), nullif(ex->>'memory','')),
    storage_type      = coalesce(nullif(storage_type,''), nullif(ex->>'storage_type','')),
    storage_capacity  = coalesce(nullif(storage_capacity,''), nullif(ex->>'storage_capacity','')),
    screen_size       = coalesce(nullif(screen_size,''), nullif(ex->>'screen_size','')),
    os                = coalesce(nullif(os,''), nullif(ex->>'os','')),
    office_supported  = coalesce(office_supported, (nullif(ex->>'office_supported',''))::boolean, false),
    webcam            = coalesce(webcam, (nullif(ex->>'webcam',''))::boolean),
    wifi              = coalesce(wifi, (nullif(ex->>'wifi',''))::boolean),
    bluetooth         = coalesce(bluetooth, (nullif(ex->>'bluetooth',''))::boolean),
    numpad            = coalesce(numpad, (nullif(ex->>'numpad',''))::boolean),
    accessories       = coalesce(nullif(accessories,''), nullif(ex->>'accessories','')),
    rakuten_synced_at = now()
  where code = p_code
  returning * into after_row;

  after_snap := to_jsonb(after_row) - 'updated_at' - 'rakuten_synced_at';
  v_changed := before_snap is distinct from after_snap;

  -- 出品先（楽天）への紐付けは、商品×チャネルの掲載情報テーブルへ
  if v_item_code is not null then
    if not exists (select 1 from public.inventory_channel_listings
                    where product_code = p_code and channel = 'rakuten') then
      insert into public.inventory_channel_listings
        (product_code, channel, state, sku, url, price, api_synced_at, api_sync_status, updated_at)
      values (p_code, 'rakuten', '出品中', v_item_code, v_url, v_price, now(), 'ok', now());
      v_chan_new := true;
    else
      update public.inventory_channel_listings set
        sku = coalesce(sku, v_item_code),
        url = coalesce(url, v_url),
        api_synced_at = now(),
        api_sync_status = 'ok',
        updated_at = case when sku is null or url is null then now() else updated_at end
      where product_code = p_code and channel = 'rakuten';
    end if;
  end if;

  if v_changed or v_chan_new then
    insert into public.inventory_transactions (actor, ref_kind, ref_id, label, action, before_value, after_value)
    values ('楽天連携', 'product', p_code, coalesce(after_row.name, after_row.model), '楽天連携で補完',
            null, coalesce(v_item_code, ''));
  end if;

  return jsonb_build_object('product', to_jsonb(after_row), 'changed', (v_changed or v_chan_new));
end $$;

comment on function public.inv_rakuten_apply_one is
  '楽天から取得した1商品ぶんのデータで、指定した商品コードの不足情報だけを埋める。
   出品先の紐付けは inventory_channel_listings（商品×チャネル）に持つ。
   すでに値が入っている列は上書きしない。実在庫（inventory_items）は作らない。';

grant execute on function public.inv_rakuten_apply_one(text,jsonb) to authenticated;

create or replace function public.inv_rakuten_sync_apply(p_items jsonb)
returns jsonb
language plpgsql security invoker set search_path = public as $$
declare
  it           jsonb;
  v_item_code  text;
  v_model      text;
  v_maker      text;
  v_name       text;
  v_norm_model text;
  v_code       text;
  v_candidates text[];
  v_result     jsonb;
  created      jsonb := '[]'::jsonb;
  updated      jsonb := '[]'::jsonb;
  unchanged    jsonb := '[]'::jsonb;
  needs_review jsonb := '[]'::jsonb;
  errs         jsonb := '[]'::jsonb;
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;

  for it in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    v_candidates := null;
    begin
      v_item_code := nullif(btrim(coalesce(it->>'item_code','')), '');
      if v_item_code is null then
        errs := errs || jsonb_build_object('item_code', it->>'item_code', 'message', '楽天商品コードがありません');
        continue;
      end if;
      v_model := nullif(btrim(coalesce(it->>'model','')), '');
      v_maker := nullif(btrim(coalesce(it->>'maker','')), '');
      v_name  := nullif(btrim(coalesce(it->>'name','')), '');
      v_norm_model := case when v_model is not null then public.inv_norm_model(v_model) end;
      v_code := null;

      -- すでに紐付いている楽天商品は再検索しない（商品×チャネルの掲載情報から引く）
      select product_code into v_code
        from public.inventory_channel_listings
       where channel = 'rakuten' and sku = v_item_code
       limit 1;

      if v_code is null and v_norm_model is not null then
        select array_agg(code) into v_candidates
          from public.inventory_products
         where public.inv_norm_model(coalesce(nullif(model,''), name)) = v_norm_model;
      end if;

      if v_code is null and (v_candidates is null or array_length(v_candidates,1) is null)
         and v_maker is not null and v_norm_model is not null then
        select array_agg(code) into v_candidates
          from public.inventory_products
         where lower(coalesce(maker,'')) = lower(v_maker)
           and public.inv_norm_model(coalesce(nullif(model,''), name)) like '%'||v_norm_model||'%';
      end if;

      if v_code is null and (v_candidates is null or array_length(v_candidates,1) is null)
         and v_name is not null and v_norm_model is not null then
        select array_agg(code) into v_candidates
          from public.inventory_products
         where name = v_name
           and public.inv_norm_model(coalesce(nullif(model,''), name)) like '%'||v_norm_model||'%';
      end if;

      if v_code is not null then
        v_result := public.inv_rakuten_apply_one(v_code, it);
        if (v_result->>'changed')::boolean then updated := updated || to_jsonb(v_code);
        else unchanged := unchanged || to_jsonb(v_code); end if;
      elsif v_candidates is not null and array_length(v_candidates,1) = 1 then
        v_result := public.inv_rakuten_apply_one(v_candidates[1], it);
        if (v_result->>'changed')::boolean then updated := updated || to_jsonb(v_candidates[1]);
        else unchanged := unchanged || to_jsonb(v_candidates[1]); end if;
      elsif v_candidates is not null and array_length(v_candidates,1) > 1 then
        needs_review := needs_review || jsonb_build_object(
          'item_code', v_item_code, 'name', v_name, 'model', v_model,
          'candidates', to_jsonb(v_candidates), 'item', it);
      else
        v_code := public.inv_next_id('P', 5);
        insert into public.inventory_products (code, name, kind, maker, model)
        values (v_code, coalesce(v_name, v_model, '(名称未設定)'), 'individual', v_maker, v_model);
        perform public.inv_rakuten_apply_one(v_code, it);
        created := created || to_jsonb(v_code);
      end if;
    exception when others then
      errs := errs || jsonb_build_object('item_code', v_item_code, 'message', sqlerrm);
    end;
  end loop;

  return jsonb_build_object(
    'created', created, 'updated', updated, 'unchanged', unchanged,
    'needs_review', needs_review, 'errors', errs,
    'created_count', jsonb_array_length(created), 'updated_count', jsonb_array_length(updated),
    'unchanged_count', jsonb_array_length(unchanged),
    'needs_review_count', jsonb_array_length(needs_review), 'error_count', jsonb_array_length(errs)
  );
end $$;

comment on function public.inv_rakuten_sync_apply is
  '楽天から取得した商品配列を、既存の商品マスターと照合して不足情報を補完する。
   候補が複数あるものは needs_review に積み、自動では選ばない。実在庫は作らない。';

grant execute on function public.inv_rakuten_sync_apply(jsonb) to authenticated;

create or replace function public.inv_rakuten_link_confirm(
  p_code text,
  p_item jsonb
) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  if not public.inv_can_edit() then
    raise exception '操作する権限がありません（閲覧のみ）';
  end if;
  return public.inv_rakuten_apply_one(p_code, p_item);
end $$;

comment on function public.inv_rakuten_link_confirm is
  '「楽天商品候補を選択」で、人が選んだ商品コードに楽天商品を紐付ける。';

grant execute on function public.inv_rakuten_link_confirm(text,jsonb) to authenticated;

-- ------------------------------------------------------------
-- 8) inventory_channel_listings の権限・RLS
-- ------------------------------------------------------------
grant select, insert, update, delete on public.inventory_channel_listings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.inventory_channel_listings enable row level security;

drop policy if exists "inventory_channel_listings read" on public.inventory_channel_listings;
create policy "inventory_channel_listings read" on public.inventory_channel_listings
  for select to authenticated using (true);

drop policy if exists "inventory_channel_listings write" on public.inventory_channel_listings;
create policy "inventory_channel_listings write" on public.inventory_channel_listings
  for all to authenticated
  using (public.inv_can_edit()) with check (public.inv_can_edit());

-- ============================================================
-- 確認：inventory_channels は個体（item_id not null）だけになったはず。
--       P-00410 の20台は inventory_channels に残り、
--       P-00410/rakuten の掲載情報1件は inventory_channel_listings にあるはず。
-- ============================================================
select 'inventory_channelsに残る商品まるごとの行（0件のはず）' as check_name, count(*) as n
  from public.inventory_channels where item_id is null
union all
select 'inventory_channel_listingsの件数', count(*) from public.inventory_channel_listings;
